#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Golem1

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_DraconiaCharacter_base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Golem1.BP_Golem1_C
// 0x0020 (0x0CC0 - 0x0CA0)
class ABP_Golem1_C final : public ABP_DraconiaCharacter_base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Golem1_C;                        // 0x0CA0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCapsuleComponent*                      Cloth_Collider_1;                                  // 0x0CA8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPhysicalAnimationComponent*            PhysicalAnimation;                                 // 0x0CB0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Golem1(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Golem1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Golem1_C")
	}
	static class ABP_Golem1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Golem1_C>();
	}
};
DUMPER7_ASSERTS_ABP_Golem1_C;

SDK_NAMESPACE_END
