#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_VelocitySound_Flying

#include "Basic.hpp"

#include "GC_VelocitySound_base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GC_VelocitySound_Flying.GC_VelocitySound_Flying_C
// 0x0000 (0x03A0 - 0x03A0)
class AGC_VelocitySound_Flying_C final : public AGC_VelocitySound_base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_VelocitySound_Flying_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_VelocitySound_Flying_C")
	}
	static class AGC_VelocitySound_Flying_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_VelocitySound_Flying_C>();
	}
};
DUMPER7_ASSERTS_AGC_VelocitySound_Flying_C;

SDK_NAMESPACE_END
