#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ConstructionMode

#include "Basic.hpp"

#include "W_ConstructionMode_classes.hpp"
#include "W_ConstructionMode_parameters.hpp"


SDK_NAMESPACE_START

// Function W_ConstructionMode.W_ConstructionMode_C.Update Placement Return Code Text
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_ConstructionMode_C::Update_Placement_Return_Code_Text()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ConstructionMode_C", "Update Placement Return Code Text");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_ConstructionMode.W_ConstructionMode_C.Update Clan Placement Text
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_ConstructionMode_C::Update_Clan_Placement_Text()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ConstructionMode_C", "Update Clan Placement Text");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_ConstructionMode.W_ConstructionMode_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ConstructionMode_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ConstructionMode_C", "Tick");

	Params::W_ConstructionMode_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ConstructionMode.W_ConstructionMode_C.OnConstructionAdjustmentChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// EConstructionPlacementMode              NewMode                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ConstructionMode_C::OnConstructionAdjustmentChanged(EConstructionPlacementMode NewMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ConstructionMode_C", "OnConstructionAdjustmentChanged");

	Params::W_ConstructionMode_C_OnConstructionAdjustmentChanged Parms{};

	Parms.NewMode = NewMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ConstructionMode.W_ConstructionMode_C.ExecuteUbergraph_W_ConstructionMode
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ConstructionMode_C::ExecuteUbergraph_W_ConstructionMode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ConstructionMode_C", "ExecuteUbergraph_W_ConstructionMode");

	Params::W_ConstructionMode_C_ExecuteUbergraph_W_ConstructionMode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ConstructionMode.W_ConstructionMode_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_ConstructionMode_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ConstructionMode_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
