#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Notification_basic

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Draconia_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_Notification_basic.W_Notification_basic_C
// 0x0040 (0x0370 - 0x0330)
class UW_Notification_basic_C final : public UDNotificationBaseWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             Text_NotificationMessage3;                         // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_NotificationMessage2;                         // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_NotificationMessage1;                         // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_NotificationHeader;                           // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Main;                                      // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeIn;                                            // 0x0360(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           EndTimer;                                          // 0x0368(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void Setup_Notification_Message(const class FString& inHeader, const TArray<class FString>& inMessages);
	void RemoveNotification();
	void Remove();
	void Notification_Lifetime_Ended();
	void InitializeNotification(const class FString& HeaderText, const TArray<class FString>& MessageLines, float Duration, class FName NotifyID);
	void Get_Message_Lines(TArray<class UTextBlock*>* Array);
	void Fade_Out_and_Remove();
	void ExecuteUbergraph_W_Notification_basic(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_Notification_basic_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_Notification_basic_C")
	}
	static class UW_Notification_basic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_Notification_basic_C>();
	}
};
DUMPER7_ASSERTS_UW_Notification_basic_C;

SDK_NAMESPACE_END
