#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_QuitPanel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WBP_Panel_Base_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_QuitPanel.WBP_QuitPanel_C
// 0x0030 (0x02B8 - 0x0288)
class UWBP_QuitPanel_C final : public UWBP_Panel_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_QuitPanel_C;                    // 0x0288(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHorizontalBox*                         btnContainer;                                      // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button1_C*                         cancelBtn;                                         // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button1_C*                         quitBtn;                                           // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScrollBox_0;                                       // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_SettingHeaderBar_C*                SettingHeaderBar;                                  // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_QuitPanel(int32 EntryPoint);
	void BndEvt__Button1_0_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature();
	void BndEvt__Button1_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature();
	struct FEventReply OnPreviewKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_QuitPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_QuitPanel_C")
	}
	static class UWBP_QuitPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_QuitPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_QuitPanel_C;

SDK_NAMESPACE_END
