#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Cards

#include "Basic.hpp"

#include "FItemSound_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "FLabelStyle_structs.hpp"
#include "FButtonStyle_structs.hpp"
#include "WBP_ControlItem_Base_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Cards.WBP_Cards_C
// 0x04A0 (0x0860 - 0x03C0)
class UWBP_Cards_C final : public UWBP_ControlItem_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_Cards_C;                        // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                border_fx;                                         // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                btn;                                               // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_104;                                         // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             line_1_text;                                       // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             line_2_text;                                       // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Line_1;                                            // 0x03F0(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	class FText                                   Line_2;                                            // 0x0408(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	class UTexture2D*                             Image;                                             // 0x0420(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnClicked;                                         // 0x0428(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnHover;                                           // 0x0438(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnUnhover;                                         // 0x0448(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FFItemSound                            ButtonSound;                                       // 0x0458(0x0020)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	EHorizontalAlignment                          LabelHorizontalAlignment;                          // 0x0478(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_479[0x3];                                      // 0x0479(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFLabelStyle                           LabelColor;                                        // 0x047C(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_4AC[0x4];                                      // 0x04AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFButtonStyle                          ButtonStyle;                                       // 0x04B0(0x0220)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	struct FSlateFontInfo                         LabelFont;                                         // 0x06D0(0x0050)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	struct FSlateBrush                            HoverFX;                                           // 0x0720(0x0088)(Edit, BlueprintVisible, ExposeOnSpawn)
	struct FMargin                                FXPadding;                                         // 0x07A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	struct FMargin                                LabelPadding;                                      // 0x07B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	EHorizontalAlignment                          Line2LabelHorizontalAlignment;                     // 0x07C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_7C9[0x3];                                      // 0x07C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFLabelStyle                           Line2LabelColor;                                   // 0x07CC(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_7FC[0x4];                                      // 0x07FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateFontInfo                         Line2LabelFont;                                    // 0x0800(0x0050)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	struct FMargin                                Line2LabelPadding;                                 // 0x0850(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_WBP_Cards(int32 EntryPoint);
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
	void PreConstruct(bool IsDesignTime);
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void HoverDeselect();
	void HoverSelect();
	void OnClick();
	void RemoveFocus();
	void SetFocus();
	void UpdateWidget();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Cards_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Cards_C")
	}
	static class UWBP_Cards_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Cards_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Cards_C;

SDK_NAMESPACE_END
