#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Wi_SpawnScreen

#include "Basic.hpp"

#include "Wi_SpawnScreen_classes.hpp"
#include "Wi_SpawnScreen_parameters.hpp"


SDK_NAMESPACE_START

// Function Wi_SpawnScreen.Wi_SpawnScreen_C.ExecuteUbergraph_Wi_SpawnScreen
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWi_SpawnScreen_C::ExecuteUbergraph_Wi_SpawnScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_SpawnScreen_C", "ExecuteUbergraph_Wi_SpawnScreen");

	Params::Wi_SpawnScreen_C_ExecuteUbergraph_Wi_SpawnScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Wi_SpawnScreen.Wi_SpawnScreen_C.BndEvt__SpawnBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_SpawnScreen_C::BndEvt__SpawnBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_SpawnScreen_C", "BndEvt__SpawnBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_SpawnScreen.Wi_SpawnScreen_C.BndEvt__IR_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_SpawnScreen_C::BndEvt__IR_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_SpawnScreen_C", "BndEvt__IR_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_SpawnScreen.Wi_SpawnScreen_C.BndEvt__FS_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_SpawnScreen_C::BndEvt__FS_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_SpawnScreen_C", "BndEvt__FS_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_SpawnScreen.Wi_SpawnScreen_C.BndEvt__MFE_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_SpawnScreen_C::BndEvt__MFE_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_SpawnScreen_C", "BndEvt__MFE_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_SpawnScreen.Wi_SpawnScreen_C.FinishSpawn
// (BlueprintCallable, BlueprintEvent)

void UWi_SpawnScreen_C::FinishSpawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_SpawnScreen_C", "FinishSpawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_SpawnScreen.Wi_SpawnScreen_C.BndEvt__SS_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_SpawnScreen_C::BndEvt__SS_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_SpawnScreen_C", "BndEvt__SS_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_SpawnScreen.Wi_SpawnScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWi_SpawnScreen_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_SpawnScreen_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_SpawnScreen.Wi_SpawnScreen_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWi_SpawnScreen_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_SpawnScreen_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_SpawnScreen.Wi_SpawnScreen_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWi_SpawnScreen_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_SpawnScreen_C", "PreConstruct");

	Params::Wi_SpawnScreen_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
