#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Frog

#include "Basic.hpp"

#include "ABP_Dinosaur_classes.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass ABP_Frog.ABP_Frog_C
// 0x0000 (0x275E0 - 0x275E0)
class UABP_Frog_C final : public UABP_Dinosaur_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Frog_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Frog_C")
	}
	static class UABP_Frog_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Frog_C>();
	}
};
DUMPER7_ASSERTS_UABP_Frog_C;

SDK_NAMESPACE_END
