#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GoreEggCarnivoreSmall

#include "Basic.hpp"

#include "BP_GoreEggBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GoreEggCarnivoreSmall.BP_GoreEggCarnivoreSmall_C
// 0x0000 (0x0460 - 0x0460)
class ABP_GoreEggCarnivoreSmall_C final : public ABP_GoreEggBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GoreEggCarnivoreSmall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GoreEggCarnivoreSmall_C")
	}
	static class ABP_GoreEggCarnivoreSmall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GoreEggCarnivoreSmall_C>();
	}
};
DUMPER7_ASSERTS_ABP_GoreEggCarnivoreSmall_C;

SDK_NAMESPACE_END
