#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CalendarUtils

#include "Basic.hpp"

#include "CalendarUtils_classes.hpp"
#include "CalendarUtils_parameters.hpp"


SDK_NAMESPACE_START

// Function CalendarUtils.CalendarUtils_C.GetDayOfWeek
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FDateTime&                 CurrentDay                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    WeekStartsOnMonday                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  DayOfWeekIndex                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCalendarUtils_C::GetDayOfWeek(const struct FDateTime& CurrentDay, bool WeekStartsOnMonday, class UObject* __WorldContext, int32* DayOfWeekIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("CalendarUtils_C", "GetDayOfWeek");

	Params::CalendarUtils_C_GetDayOfWeek Parms{};

	Parms.CurrentDay = std::move(CurrentDay);
	Parms.WeekStartsOnMonday = WeekStartsOnMonday;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (DayOfWeekIndex != nullptr)
		*DayOfWeekIndex = Parms.DayOfWeekIndex;
}


// Function CalendarUtils.CalendarUtils_C.GetNextMonth
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FDateTime&                 CurrentMonth                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FDateTime*                       NextMonth                                              (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UCalendarUtils_C::GetNextMonth(const struct FDateTime& CurrentMonth, class UObject* __WorldContext, struct FDateTime* NextMonth)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("CalendarUtils_C", "GetNextMonth");

	Params::CalendarUtils_C_GetNextMonth Parms{};

	Parms.CurrentMonth = std::move(CurrentMonth);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (NextMonth != nullptr)
		*NextMonth = std::move(Parms.NextMonth);
}


// Function CalendarUtils.CalendarUtils_C.GetPreviousMonth
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FDateTime&                 CurrentMonth                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FDateTime*                       PreviousMonth                                          (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UCalendarUtils_C::GetPreviousMonth(const struct FDateTime& CurrentMonth, class UObject* __WorldContext, struct FDateTime* PreviousMonth)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("CalendarUtils_C", "GetPreviousMonth");

	Params::CalendarUtils_C_GetPreviousMonth Parms{};

	Parms.CurrentMonth = std::move(CurrentMonth);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (PreviousMonth != nullptr)
		*PreviousMonth = std::move(Parms.PreviousMonth);
}


// Function CalendarUtils.CalendarUtils_C.IsCalendarDateRangeValid
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FCalendarDateRange&        Input                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsValid                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCalendarUtils_C::IsCalendarDateRangeValid(const struct FCalendarDateRange& Input, class UObject* __WorldContext, bool* IsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("CalendarUtils_C", "IsCalendarDateRangeValid");

	Params::CalendarUtils_C_IsCalendarDateRangeValid Parms{};

	Parms.Input = std::move(Input);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (IsValid != nullptr)
		*IsValid = Parms.IsValid;
}


// Function CalendarUtils.CalendarUtils_C.IsCalendarDateValid
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Month                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Year                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsValid                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCalendarUtils_C::IsCalendarDateValid(int32 Month, int32 Year, class UObject* __WorldContext, bool* IsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("CalendarUtils_C", "IsCalendarDateValid");

	Params::CalendarUtils_C_IsCalendarDateValid Parms{};

	Parms.Month = Month;
	Parms.Year = Year;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (IsValid != nullptr)
		*IsValid = Parms.IsValid;
}


// Function CalendarUtils.CalendarUtils_C.IsDateWithinCalendarRange
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FDateTime&                 DateToTest                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FCalendarDateRange&        RangeToTest                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Within                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCalendarUtils_C::IsDateWithinCalendarRange(const struct FDateTime& DateToTest, const struct FCalendarDateRange& RangeToTest, class UObject* __WorldContext, bool* Within)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("CalendarUtils_C", "IsDateWithinCalendarRange");

	Params::CalendarUtils_C_IsDateWithinCalendarRange Parms{};

	Parms.DateToTest = std::move(DateToTest);
	Parms.RangeToTest = std::move(RangeToTest);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Within != nullptr)
		*Within = Parms.Within;
}


// Function CalendarUtils.CalendarUtils_C.SetTextBlockStyle
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTextBlock*                       TB                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FTextBlockStyle&           TBStyle                                                (BlueprintVisible, BlueprintReadOnly, Parm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UCalendarUtils_C::SetTextBlockStyle(class UTextBlock* TB, const struct FTextBlockStyle& TBStyle, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("CalendarUtils_C", "SetTextBlockStyle");

	Params::CalendarUtils_C_SetTextBlockStyle Parms{};

	Parms.TB = TB;
	Parms.TBStyle = std::move(TBStyle);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function CalendarUtils.CalendarUtils_C.ZellerCongruence
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FDateTime&                 CurrentTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  DayInt                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCalendarUtils_C::ZellerCongruence(const struct FDateTime& CurrentTime, class UObject* __WorldContext, int32* DayInt)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("CalendarUtils_C", "ZellerCongruence");

	Params::CalendarUtils_C_ZellerCongruence Parms{};

	Parms.CurrentTime = std::move(CurrentTime);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (DayInt != nullptr)
		*DayInt = Parms.DayInt;
}


SDK_NAMESPACE_END
