#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_Weather_Configuration

#include "Basic.hpp"

#include "UDS_SharedConfig_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass UDS_Weather_Configuration.UDS_Weather_Configuration_C
// 0x02F0 (0x03F8 - 0x0108)
class UUDS_Weather_Configuration_C final : public UUDS_SharedConfig_C
{
public:
	TMap<class UUDS_Weather_Settings_C*, double>  Weather_Probability__Summer_;                      // 0x0108(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UUDS_Weather_Settings_C*, double>  Weather_Probability__Autumn_;                      // 0x0158(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UUDS_Weather_Settings_C*, double>  Weather_Probability__Winter_;                      // 0x01A8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UUDS_Weather_Settings_C*, double>  Weather_Probability__Spring_;                      // 0x01F8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UUDS_Weather_Settings_C*, double>  Weather_Specific_Interval_Multipliers;             // 0x0248(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UPhysicalMaterial*>              PhysMats_Disable_Snow;                             // 0x0298(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UPhysicalMaterial*>              PhysMats_Disable_Puddles;                          // 0x02A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UUDS_Weather_Settings_C*, double>  Radial_Storm_Probabilities__Spring_;               // 0x02B8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UUDS_Weather_Settings_C*, double>  Radial_Storm_Probabilities__Summer_;               // 0x0308(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UUDS_Weather_Settings_C*, double>  Radial_Storm_Probabilities__Autumn_;               // 0x0358(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UUDS_Weather_Settings_C*, double>  Radial_Storm_Probabilities__Winter_;               // 0x03A8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UDS_Weather_Configuration_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UDS_Weather_Configuration_C")
	}
	static class UUDS_Weather_Configuration_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUDS_Weather_Configuration_C>();
	}
};
DUMPER7_ASSERTS_UUDS_Weather_Configuration_C;

SDK_NAMESPACE_END
