#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Puddle_Fluid_Volume_Interface

#include "Basic.hpp"

#include "Puddle_Fluid_Volume_Interface_classes.hpp"
#include "Puddle_Fluid_Volume_Interface_parameters.hpp"


SDK_NAMESPACE_START

// Function Puddle_Fluid_Volume_Interface.Puddle_Fluid_Volume_Interface_C.Interact with Puddle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Diameter                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Speed                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Last_Trace_Location                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Ground_Height                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 Effective_Depth                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IPuddle_Fluid_Volume_Interface_C::Interact_with_Puddle(const struct FVector& Location, double Diameter, double Speed, const struct FVector& Last_Trace_Location, double Ground_Height, double* Effective_Depth)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("Puddle_Fluid_Volume_Interface_C", "Interact with Puddle");

	Params::Puddle_Fluid_Volume_Interface_C_Interact_with_Puddle Parms{};

	Parms.Location = std::move(Location);
	Parms.Diameter = Diameter;
	Parms.Speed = Speed;
	Parms.Last_Trace_Location = std::move(Last_Trace_Location);
	Parms.Ground_Height = Ground_Height;

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Effective_Depth != nullptr)
		*Effective_Depth = Parms.Effective_Depth;
}


SDK_NAMESPACE_END
