#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomWeatherVariation_State

#include "Basic.hpp"

#include "UDS_RandomWeatherTiming_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct RandomWeatherVariation_State.RandomWeatherVariation_State
// 0x0040 (0x0040 - 0x0000)
struct FRandomWeatherVariation_State final
{
public:
	EUDS_RandomWeatherTiming                      Mode_29_E53E8F9C40E9C74B1489D0A581FF28D2;          // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                TargetRandomWeatherType_37_BBFDBC5E46C25F1DFB0037A44AB6D268; // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CurrentLerpAlpha_38_659CCE944698D027E31F1C9F648EBD85; // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CurrentTimerLength_39_6CC4C61F4528647B419BE189C0944ADF; // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ChangeTimer_40_28CED07F4F2AE061871DB595D0DD4C66;   // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                LastRandomWeatherType_41_4367B1AC4E64A2564E3960B3ED6E25D8; // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class UObject*>                        Forecast_36_FB829F034AD4245050A506B528B86CC0;      // 0x0030(0x0010)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FRandomWeatherVariation_State;

SDK_NAMESPACE_END
