#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SocketSubsystemEIK

#include "Basic.hpp"

#include "OnlineSubsystemUtils_classes.hpp"


SDK_NAMESPACE_START

// Class SocketSubsystemEIK.NetConnectionEIK
// 0x0008 (0x1E50 - 0x1E48)
class UNetConnectionEIK final : public UIpConnection
{
public:
	uint8                                         Pad_1E48[0x8];                                     // 0x1E48(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NetConnectionEIK")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NetConnectionEIK")
	}
	static class UNetConnectionEIK* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNetConnectionEIK>();
	}
};
DUMPER7_ASSERTS_UNetConnectionEIK;

// Class SocketSubsystemEIK.NetDriverEIKBase
// 0x0008 (0x0860 - 0x0858)
class UNetDriverEIKBase : public UIpNetDriver
{
public:
	bool                                          bIsPassthrough;                                    // 0x0858(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsUsingP2PSockets;                                // 0x0859(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_85A[0x6];                                      // 0x085A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NetDriverEIKBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NetDriverEIKBase")
	}
	static class UNetDriverEIKBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNetDriverEIKBase>();
	}
};
DUMPER7_ASSERTS_UNetDriverEIKBase;

SDK_NAMESPACE_END
