#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Wi_InteractHintText

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass Wi_InteractHintText.Wi_InteractHintText_C
// 0x0048 (0x02C8 - 0x0280)
class UWi_InteractHintText_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeText;                                          // 0x0288(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_0;                                     // 0x0290(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Hint;                                              // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   HintText;                                          // 0x02A0(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          IsPersistent;                                      // 0x02B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          HideHUD;                                           // 0x02B9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BA[0x6];                                      // 0x02BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ADragonsPC_C*                           Dragons_Player_Controller;                         // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void Destruct();
	void ExecuteUbergraph_Wi_InteractHintText(int32 EntryPoint);
	ESlateVisibility GetVisibility_0();
	void PreConstruct(bool IsDesignTime);
	void Remove();
	void SettingsChanged_Event_0();
	void ToggleHUD_Event_0(bool HideHUD_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Wi_InteractHintText_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Wi_InteractHintText_C")
	}
	static class UWi_InteractHintText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWi_InteractHintText_C>();
	}
};
DUMPER7_ASSERTS_UWi_InteractHintText_C;

SDK_NAMESPACE_END
