#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoColorSet_PartyDodos

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DinoColorSet_PartyDodos.DinoColorSet_PartyDodos_C
// 0x0000 (0x0268 - 0x0268)
class UDinoColorSet_PartyDodos_C final : public UPrimalColorSet
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DinoColorSet_PartyDodos_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DinoColorSet_PartyDodos_C")
	}
	static class UDinoColorSet_PartyDodos_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoColorSet_PartyDodos_C>();
	}
};
DUMPER7_ASSERTS_UDinoColorSet_PartyDodos_C;

SDK_NAMESPACE_END
