#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_ZiplineAmmo

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EngramEntry_ZiplineAmmo.EngramEntry_ZiplineAmmo_C
// 0x0000 (0x00B0 - 0x00B0)
class UEngramEntry_ZiplineAmmo_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EngramEntry_ZiplineAmmo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EngramEntry_ZiplineAmmo_C")
	}
	static class UEngramEntry_ZiplineAmmo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_ZiplineAmmo_C>();
	}
};
DUMPER7_ASSERTS_UEngramEntry_ZiplineAmmo_C;

SDK_NAMESPACE_END
