#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HairStrandsCore

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "MovieScene_structs.hpp"


SDK_NAMESPACE_START

// Enum HairStrandsCore.EGroomCacheImportType
// NumValues: 0x0005
enum class EGroomCacheImportType : uint8
{
	None                                     = 0,
	Strands                                  = 1,
	Guides                                   = 2,
	All                                      = 3,
	EGroomCacheImportType_MAX                = 4,
};

// Enum HairStrandsCore.EHairAtlasTextureType
// NumValues: 0x0007
enum class EHairAtlasTextureType : uint8
{
	Depth                                    = 0,
	Tangent                                  = 1,
	Attribute                                = 2,
	Coverage                                 = 3,
	AuxilaryData                             = 4,
	Material                                 = 5,
	EHairAtlasTextureType_MAX                = 6,
};

// Enum HairStrandsCore.EHairCardsSourceType
// NumValues: 0x0003
enum class EHairCardsSourceType : uint8
{
	Procedural                               = 0,
	Imported                                 = 1,
	EHairCardsSourceType_MAX                 = 2,
};

// Enum HairStrandsCore.EHairCardsGuideType
// NumValues: 0x0003
enum class EHairCardsGuideType : uint8
{
	Generated                                = 0,
	GuideBased                               = 1,
	EHairCardsGuideType_MAX                  = 2,
};

// Enum HairStrandsCore.EHairTextureLayout
// NumValues: 0x0005
enum class EHairTextureLayout : uint8
{
	Layout0                                  = 0,
	Layout1                                  = 1,
	Layout2                                  = 2,
	Layout3                                  = 3,
	EHairTextureLayout_MAX                   = 4,
};

// Enum HairStrandsCore.EHairInterpolationQuality
// NumValues: 0x0005
enum class EHairInterpolationQuality : uint8
{
	Low                                      = 0,
	Medium                                   = 1,
	High                                     = 2,
	Unknown                                  = 3,
	EHairInterpolationQuality_MAX            = 4,
};

// Enum HairStrandsCore.EHairInterpolationWeight
// NumValues: 0x0006
enum class EHairInterpolationWeight : uint8
{
	Parametric                               = 0,
	Root                                     = 1,
	Index                                    = 2,
	Distance                                 = 3,
	Unknown                                  = 4,
	EHairInterpolationWeight_MAX             = 5,
};

// Enum HairStrandsCore.EGroomGeometryType
// NumValues: 0x0004
enum class EGroomGeometryType : uint8
{
	Strands                                  = 0,
	Cards                                    = 1,
	Meshes                                   = 2,
	EGroomGeometryType_MAX                   = 3,
};

// Enum HairStrandsCore.EGroomBindingType
// NumValues: 0x0004
enum class EGroomBindingType : uint8
{
	NoneBinding                              = 0,
	Rigid                                    = 1,
	Skinning                                 = 2,
	EGroomBindingType_MAX                    = 3,
};

// Enum HairStrandsCore.EGroomOverrideType
// NumValues: 0x0004
enum class EGroomOverrideType : uint8
{
	Auto                                     = 0,
	Enable                                   = 1,
	Disable                                  = 2,
	EGroomOverrideType_MAX                   = 3,
};

// Enum HairStrandsCore.EGroomGuideType
// NumValues: 0x0004
enum class EGroomGuideType : uint8
{
	Imported                                 = 0,
	Generated                                = 1,
	Rigged                                   = 2,
	EGroomGuideType_MAX                      = 3,
};

// Enum HairStrandsCore.EGroomLODMode
// NumValues: 0x0004
enum class EGroomLODMode : uint8
{
	Default                                  = 0,
	Manual                                   = 1,
	Auto                                     = 2,
	EGroomLODMode_MAX                        = 3,
};

// Enum HairStrandsCore.EGroomNiagaraSolvers
// NumValues: 0x0005
enum class EGroomNiagaraSolvers : uint8
{
	None                                     = 0,
	CosseratRods                             = 2,
	AngularSprings                           = 4,
	CustomSolver                             = 8,
	EGroomNiagaraSolvers_MAX                 = 9,
};

// Enum HairStrandsCore.EGroomStrandsSize
// NumValues: 0x0007
enum class EGroomStrandsSize : uint8
{
	None                                     = 0,
	Size2                                    = 2,
	Size4                                    = 4,
	Size8                                    = 8,
	Size16                                   = 16,
	Size32                                   = 32,
	EGroomStrandsSize_MAX                    = 33,
};

// Enum HairStrandsCore.EGroomInterpolationType
// NumValues: 0x0005
enum class EGroomInterpolationType : uint8
{
	None                                     = 0,
	RigidTransform                           = 2,
	OffsetTransform                          = 4,
	SmoothTransform                          = 8,
	EGroomInterpolationType_MAX              = 9,
};

// Enum HairStrandsCore.EGroomBindingMeshType
// NumValues: 0x0003
enum class EGroomBindingMeshType : uint8
{
	SkeletalMesh                             = 0,
	GeometryCache                            = 1,
	EGroomBindingMeshType_MAX                = 2,
};

// Enum HairStrandsCore.EGroomBindingAsyncProperties
// NumValues: 0x000E
enum class EGroomBindingAsyncProperties : uint64
{
	None                                     = 0,
	GroomBindingType                         = 1,
	Groom                                    = 2,
	SourceSkeletalMesh                       = 4,
	TargetSkeletalMesh                       = 8,
	SourceGeometryCache                      = 16,
	TargetGeometryCache                      = 32,
	NumInterpolationPoints                   = 64,
	MatchingSection                          = 128,
	GroupInfos                               = 256,
	HairGroupResources                       = 512,
	HairGroupPlatformData                    = 1024,
	All                                      = 18446744073709551615,
	EGroomBindingAsyncProperties_MAX         = 1025,
};

// Enum HairStrandsCore.EGroomCacheAttributes
// NumValues: 0x0009
enum class EGroomCacheAttributes : uint8
{
	None                                     = 0,
	Position                                 = 1,
	Width                                    = 2,
	Color                                    = 4,
	PositionWidth                            = 3,
	PositionColor                            = 5,
	WidthColor                               = 5,
	PositionWidthColor                       = 7,
	EGroomCacheAttributes_MAX                = 8,
};

// Enum HairStrandsCore.EGroomCacheType
// NumValues: 0x0004
enum class EGroomCacheType : uint8
{
	None                                     = 0,
	Strands                                  = 1,
	Guides                                   = 2,
	EGroomCacheType_MAX                      = 3,
};

// Enum HairStrandsCore.EGroomBasisType
// NumValues: 0x0007
enum class EGroomBasisType : uint8
{
	NoBasis                                  = 0,
	BezierBasis                              = 1,
	BsplineBasis                             = 2,
	CatmullromBasis                          = 3,
	HermiteBasis                             = 4,
	PowerBasis                               = 5,
	EGroomBasisType_MAX                      = 6,
};

// Enum HairStrandsCore.EGroomCurveType
// NumValues: 0x0004
enum class EGroomCurveType : uint8
{
	Cubic                                    = 0,
	Linear                                   = 1,
	VariableOrder                            = 2,
	EGroomCurveType_MAX                      = 3,
};

// Enum HairStrandsCore.EFollicleMaskChannel
// NumValues: 0x0005
enum class EFollicleMaskChannel : uint8
{
	R                                        = 0,
	G                                        = 1,
	B                                        = 2,
	A                                        = 3,
	EFollicleMaskChannel_MAX                 = 4,
};

// Enum HairStrandsCore.EStrandsTexturesTraceType
// NumValues: 0x0004
enum class EStrandsTexturesTraceType : uint8
{
	TraceInside                              = 0,
	TraceOuside                              = 1,
	TraceBidirectional                       = 2,
	EStrandsTexturesTraceType_MAX            = 3,
};

// Enum HairStrandsCore.EStrandsTexturesMeshType
// NumValues: 0x0003
enum class EStrandsTexturesMeshType : uint8
{
	Static                                   = 0,
	Skeletal                                 = 1,
	EStrandsTexturesMeshType_MAX             = 2,
};

// Enum HairStrandsCore.EGroomInterpolationQuality
// NumValues: 0x0005
enum class EGroomInterpolationQuality : uint8
{
	Low                                      = 0,
	Medium                                   = 1,
	High                                     = 2,
	Unknown                                  = 3,
	EGroomInterpolationQuality_MAX           = 4,
};

// Enum HairStrandsCore.EGroomInterpolationWeight
// NumValues: 0x0005
enum class EGroomInterpolationWeight : uint8
{
	Parametric                               = 0,
	Root                                     = 1,
	Index                                    = 2,
	Unknown                                  = 3,
	EGroomInterpolationWeight_MAX            = 4,
};

// ScriptStruct HairStrandsCore.GroomConversionSettings
// 0x0030 (0x0030 - 0x0000)
struct FGroomConversionSettings final
{
public:
	struct FVector                                Rotation;                                          // 0x0000(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Scale;                                             // 0x0018(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGroomConversionSettings;

// ScriptStruct HairStrandsCore.GroomCacheImportSettings
// 0x0068 (0x0068 - 0x0000)
struct FGroomCacheImportSettings final
{
public:
	bool                                          bImportGroomCache;                                 // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGroomCacheImportType                         ImportType;                                        // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         FrameStart;                                        // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FrameEnd;                                          // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSkipEmptyFrames;                                  // 0x000C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportGroomAsset;                                 // 0x000D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoftObjectPath                        GroomAsset;                                        // 0x0010(0x0020)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bOverrideConversionSettings;                       // 0x0030(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGroomConversionSettings               ConversionSettings;                                // 0x0038(0x0030)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGroomCacheImportSettings;

// ScriptStruct HairStrandsCore.HairGroupDesc
// 0x0040 (0x0040 - 0x0000)
struct FHairGroupDesc final
{
public:
	float                                         HairLength;                                        // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HairWidth;                                         // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          HairWidth_Override;                                // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HairRootScale;                                     // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          HairRootScale_Override;                            // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HairTipScale;                                      // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          HairTipScale_Override;                             // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HairShadowDensity;                                 // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          HairShadowDensity_Override;                        // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HairRaytracingRadiusScale;                         // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          HairRaytracingRadiusScale_Override;                // 0x0028(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseHairRaytracingGeometry;                        // 0x0029(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseHairRaytracingGeometry_Override;               // 0x002A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2B[0x1];                                       // 0x002B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LODBias;                                           // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseStableRasterization;                           // 0x0030(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseStableRasterization_Override;                  // 0x0031(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bScatterSceneLighting;                             // 0x0032(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bScatterSceneLighting_Override;                    // 0x0033(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSupportVoxelization;                              // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSupportVoxelization_Override;                     // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_36[0x2];                                       // 0x0036(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HairLengthScale;                                   // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          HairLengthScale_Override;                          // 0x003C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FHairGroupDesc;

// ScriptStruct HairStrandsCore.HairGroupLODInfo
// 0x0008 (0x0008 - 0x0000)
struct FHairGroupLODInfo final
{
public:
	int32                                         NumPoints;                                         // 0x0000(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumCurves;                                         // 0x0004(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairGroupLODInfo;

// ScriptStruct HairStrandsCore.HairGroupInfo
// 0x0038 (0x0038 - 0x0000)
struct FHairGroupInfo
{
public:
	int32                                         GroupID;                                           // 0x0000(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   GroupName;                                         // 0x0004(0x0008)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumCurves;                                         // 0x000C(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumGuides;                                         // 0x0010(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumCurveVertices;                                  // 0x0014(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumGuideVertices;                                  // 0x0018(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxCurveLength;                                    // 0x001C(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        Flags;                                             // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FHairGroupLODInfo>              LODInfos;                                          // 0x0028(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairGroupInfo;

// ScriptStruct HairStrandsCore.HairGroupsMaterial
// 0x0010 (0x0010 - 0x0000)
struct FHairGroupsMaterial final
{
public:
	class UMaterialInterface*                     Material;                                          // 0x0000(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class FName                                   SlotName;                                          // 0x0008(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairGroupsMaterial;

// ScriptStruct HairStrandsCore.HairGroupInfoWithVisibility
// 0x0008 (0x0040 - 0x0038)
struct FHairGroupInfoWithVisibility final : public FHairGroupInfo
{
public:
	bool                                          bIsVisible;                                        // 0x0038(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FHairGroupInfoWithVisibility;

// ScriptStruct HairStrandsCore.HairGroupCardsInfo
// 0x0008 (0x0008 - 0x0000)
struct FHairGroupCardsInfo final
{
public:
	int32                                         NumCards;                                          // 0x0000(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumCardVertices;                                   // 0x0004(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairGroupCardsInfo;

// ScriptStruct HairStrandsCore.HairGroupCardsTextures
// 0x0050 (0x0050 - 0x0000)
struct FHairGroupCardsTextures final
{
public:
	EHairTextureLayout                            layout;                                            // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UTexture2D*>                     Textures;                                          // 0x0008(0x0010)(Edit, ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UTexture2D*                             DepthTexture;                                      // 0x0018(0x0008)(ZeroConstructor, Deprecated, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UTexture2D*                             CoverageTexture;                                   // 0x0020(0x0008)(ZeroConstructor, Deprecated, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UTexture2D*                             TangentTexture;                                    // 0x0028(0x0008)(ZeroConstructor, Deprecated, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UTexture2D*                             AttributeTexture;                                  // 0x0030(0x0008)(ZeroConstructor, Deprecated, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UTexture2D*                             AuxilaryDataTexture;                               // 0x0038(0x0008)(ZeroConstructor, Deprecated, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UTexture2D*                             MaterialTexture;                                   // 0x0040(0x0008)(ZeroConstructor, Deprecated, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	uint8                                         Pad_48[0x8];                                       // 0x0048(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FHairGroupCardsTextures;

// ScriptStruct HairStrandsCore.HairGroupsCardsSourceDescription
// 0x00A0 (0x00A0 - 0x0000)
struct FHairGroupsCardsSourceDescription final
{
public:
	class UMaterialInterface*                     Material;                                          // 0x0000(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class FName                                   MaterialSlotName;                                  // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHairCardsSourceType                          SourceType;                                        // 0x0010(0x0001)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMesh*                            ProceduralMesh;                                    // 0x0018(0x0008)(ZeroConstructor, Deprecated, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	bool                                          bInvertUV;                                         // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHairCardsGuideType                           GuideType;                                         // 0x0021(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMesh*                            ImportedMesh;                                      // 0x0028(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	struct FHairGroupCardsTextures                Textures;                                          // 0x0030(0x0050)(Edit, NativeAccessSpecifierPublic)
	int32                                         GroupIndex;                                        // 0x0080(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LODIndex;                                          // 0x0084(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHairGroupCardsInfo                    CardsInfo;                                         // 0x0088(0x0008)(Edit, Transient, EditConst, NoDestructor, NativeAccessSpecifierPublic)
	class FString                                 ImportedMeshKey;                                   // 0x0090(0x0010)(ZeroConstructor, Transient, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairGroupsCardsSourceDescription;

// ScriptStruct HairStrandsCore.HairLODSettings
// 0x001C (0x001C - 0x0000)
struct FHairLODSettings final
{
public:
	float                                         CurveDecimation;                                   // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         VertexDecimation;                                  // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AngularThreshold;                                  // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ScreenSize;                                        // 0x000C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ThicknessScale;                                    // 0x0010(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bVisible;                                          // 0x0014(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGroomGeometryType                            GeometryType;                                      // 0x0015(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGroomBindingType                             BindingType;                                       // 0x0016(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGroomOverrideType                            Simulation;                                        // 0x0017(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGroomOverrideType                            GlobalInterpolation;                               // 0x0018(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FHairLODSettings;

// ScriptStruct HairStrandsCore.HairDecimationSettings
// 0x0008 (0x0008 - 0x0000)
struct FHairDecimationSettings final
{
public:
	float                                         CurveDecimation;                                   // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         VertexDecimation;                                  // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairDecimationSettings;

// ScriptStruct HairStrandsCore.HairInterpolationSettings
// 0x0014 (0x0014 - 0x0000)
struct FHairInterpolationSettings final
{
public:
	EGroomGuideType                               GuideType;                                         // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bOverrideGuides;                                   // 0x0001(0x0001)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HairToGuideDensity;                                // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RiggedGuideNumCurves;                              // 0x0008(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RiggedGuideNumPoints;                              // 0x000C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHairInterpolationQuality                     InterpolationQuality;                              // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHairInterpolationWeight                      InterpolationDistance;                             // 0x0011(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRandomizeGuide;                                   // 0x0012(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseUniqueGuide;                                   // 0x0013(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairInterpolationSettings;

// ScriptStruct HairStrandsCore.HairDeformationSettings
// 0x000C (0x000C - 0x0000)
struct FHairDeformationSettings final
{
public:
	bool                                          bEnableRigging;                                    // 0x0000(0x0001)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         NumCurves;                                         // 0x0004(0x0004)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumPoints;                                         // 0x0008(0x0004)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairDeformationSettings;

// ScriptStruct HairStrandsCore.HairGroupsInterpolation
// 0x0028 (0x0028 - 0x0000)
struct FHairGroupsInterpolation final
{
public:
	struct FHairDecimationSettings                DecimationSettings;                                // 0x0000(0x0008)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	struct FHairInterpolationSettings             InterpolationSettings;                             // 0x0008(0x0014)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	struct FHairDeformationSettings               RiggingSettings;                                   // 0x001C(0x000C)(NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairGroupsInterpolation;

// ScriptStruct HairStrandsCore.HairGroupsLOD
// 0x0010 (0x0010 - 0x0000)
struct FHairGroupsLOD final
{
public:
	TArray<struct FHairLODSettings>               Lods;                                              // 0x0000(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairGroupsLOD;

// ScriptStruct HairStrandsCore.HairGroupsMeshesSourceDescription
// 0x0080 (0x0080 - 0x0000)
struct FHairGroupsMeshesSourceDescription final
{
public:
	class UMaterialInterface*                     Material;                                          // 0x0000(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class FName                                   MaterialSlotName;                                  // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UStaticMesh*                            ImportedMesh;                                      // 0x0010(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	struct FHairGroupCardsTextures                Textures;                                          // 0x0018(0x0050)(Edit, NativeAccessSpecifierPublic)
	int32                                         GroupIndex;                                        // 0x0068(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LODIndex;                                          // 0x006C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ImportedMeshKey;                                   // 0x0070(0x0010)(ZeroConstructor, Transient, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairGroupsMeshesSourceDescription;

// ScriptStruct HairStrandsCore.HairSolverSettings
// 0x0040 (0x0040 - 0x0000)
struct FHairSolverSettings final
{
public:
	bool                                          EnableSimulation;                                  // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGroomNiagaraSolvers                          NiagaraSolver;                                     // 0x0001(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UNiagaraSystem>          CustomSystem;                                      // 0x0008(0x0028)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         GravityPreloading;                                 // 0x0030(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SubSteps;                                          // 0x0034(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         IterationCount;                                    // 0x0038(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceVisible;                                     // 0x003C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FHairSolverSettings;

// ScriptStruct HairStrandsCore.HairExternalForces
// 0x0038 (0x0038 - 0x0000)
struct FHairExternalForces final
{
public:
	struct FVector                                GravityVector;                                     // 0x0000(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AirDrag;                                           // 0x0018(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                AirVelocity;                                       // 0x0020(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairExternalForces;

// ScriptStruct HairStrandsCore.HairBendConstraint
// 0x0098 (0x0098 - 0x0000)
struct FHairBendConstraint final
{
public:
	bool                                          SolveBend;                                         // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ProjectBend;                                       // 0x0001(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         BendDamping;                                       // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BendStiffness;                                     // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRuntimeFloatCurve                     BendScale;                                         // 0x0010(0x0088)(Edit, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairBendConstraint;

// ScriptStruct HairStrandsCore.HairStretchConstraint
// 0x0098 (0x0098 - 0x0000)
struct FHairStretchConstraint final
{
public:
	bool                                          SolveStretch;                                      // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ProjectStretch;                                    // 0x0001(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         StretchDamping;                                    // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StretchStiffness;                                  // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRuntimeFloatCurve                     StretchScale;                                      // 0x0010(0x0088)(Edit, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairStretchConstraint;

// ScriptStruct HairStrandsCore.HairCollisionConstraint
// 0x00A8 (0x00A8 - 0x0000)
struct FHairCollisionConstraint final
{
public:
	bool                                          SolveCollision;                                    // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ProjectCollision;                                  // 0x0001(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         StaticFriction;                                    // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         KineticFriction;                                   // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StrandsViscosity;                                  // 0x000C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FIntVector                             GridDimension;                                     // 0x0010(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CollisionRadius;                                   // 0x001C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRuntimeFloatCurve                     RadiusScale;                                       // 0x0020(0x0088)(Edit, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairCollisionConstraint;

// ScriptStruct HairStrandsCore.HairMaterialConstraints
// 0x01D8 (0x01D8 - 0x0000)
struct FHairMaterialConstraints final
{
public:
	struct FHairBendConstraint                    BendConstraint;                                    // 0x0000(0x0098)(Edit, NativeAccessSpecifierPublic)
	struct FHairStretchConstraint                 StretchConstraint;                                 // 0x0098(0x0098)(Edit, NativeAccessSpecifierPublic)
	struct FHairCollisionConstraint               CollisionConstraint;                               // 0x0130(0x00A8)(Edit, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairMaterialConstraints;

// ScriptStruct HairStrandsCore.HairStrandsParameters
// 0x0098 (0x0098 - 0x0000)
struct FHairStrandsParameters final
{
public:
	EGroomStrandsSize                             StrandsSize;                                       // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         StrandsDensity;                                    // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StrandsSmoothing;                                  // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StrandsThickness;                                  // 0x000C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRuntimeFloatCurve                     ThicknessScale;                                    // 0x0010(0x0088)(Edit, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairStrandsParameters;

// ScriptStruct HairStrandsCore.HairGroupsPhysics
// 0x02E8 (0x02E8 - 0x0000)
struct FHairGroupsPhysics final
{
public:
	struct FHairSolverSettings                    SolverSettings;                                    // 0x0000(0x0040)(Edit, NativeAccessSpecifierPublic)
	struct FHairExternalForces                    ExternalForces;                                    // 0x0040(0x0038)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	struct FHairMaterialConstraints               MaterialConstraints;                               // 0x0078(0x01D8)(Edit, NativeAccessSpecifierPublic)
	struct FHairStrandsParameters                 StrandsParameters;                                 // 0x0250(0x0098)(Edit, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairGroupsPhysics;

// ScriptStruct HairStrandsCore.HairSimulationSolver
// 0x0001 (0x0001 - 0x0000)
struct FHairSimulationSolver final
{
public:
	bool                                          bEnableSimulation;                                 // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairSimulationSolver;

// ScriptStruct HairStrandsCore.HairSimulationForces
// 0x0038 (0x0038 - 0x0000)
struct FHairSimulationForces final
{
public:
	struct FVector                                GravityVector;                                     // 0x0000(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AirDrag;                                           // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                AirVelocity;                                       // 0x0020(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairSimulationForces;

// ScriptStruct HairStrandsCore.HairSimulationConstraints
// 0x0020 (0x0020 - 0x0000)
struct FHairSimulationConstraints final
{
public:
	float                                         BendDamping;                                       // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BendStiffness;                                     // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StretchDamping;                                    // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StretchStiffness;                                  // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StaticFriction;                                    // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         KineticFriction;                                   // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StrandsViscosity;                                  // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CollisionRadius;                                   // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairSimulationConstraints;

// ScriptStruct HairStrandsCore.HairSimulationSetup
// 0x0028 (0x0028 - 0x0000)
struct FHairSimulationSetup final
{
public:
	bool                                          bResetSimulation;                                  // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDebugSimulation;                                  // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLocalSimulation;                                  // 0x0002(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3[0x1];                                        // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LinearVelocityScale;                               // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AngularVelocityScale;                              // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 LocalBone;                                         // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, Interp, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TeleportDistance;                                  // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FHairSimulationSetup;

// ScriptStruct HairStrandsCore.HairSimulationSettings
// 0x0090 (0x0090 - 0x0000)
struct FHairSimulationSettings final
{
public:
	bool                                          bOverrideSettings;                                 // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHairSimulationSetup                   SimulationSetup;                                   // 0x0008(0x0028)(Edit, BlueprintVisible, Interp, NativeAccessSpecifierPublic)
	struct FHairSimulationSolver                  SolverSettings;                                    // 0x0030(0x0001)(Edit, BlueprintVisible, Interp, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHairSimulationForces                  ExternalForces;                                    // 0x0038(0x0038)(Edit, BlueprintVisible, Interp, NoDestructor, NativeAccessSpecifierPublic)
	struct FHairSimulationConstraints             MaterialConstraints;                               // 0x0070(0x0020)(Edit, BlueprintVisible, Interp, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairSimulationSettings;

// ScriptStruct HairStrandsCore.HairGeometrySettings
// 0x0010 (0x0010 - 0x0000)
struct FHairGeometrySettings final
{
public:
	float                                         HairWidth;                                         // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          HairWidth_Override;                                // 0x0004(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HairRootScale;                                     // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HairTipScale;                                      // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairGeometrySettings;

// ScriptStruct HairStrandsCore.HairShadowSettings
// 0x000C (0x000C - 0x0000)
struct FHairShadowSettings final
{
public:
	float                                         HairShadowDensity;                                 // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HairRaytracingRadiusScale;                         // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseHairRaytracingGeometry;                        // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bVoxelize;                                         // 0x0009(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FHairShadowSettings;

// ScriptStruct HairStrandsCore.HairAdvancedRenderingSettings
// 0x0002 (0x0002 - 0x0000)
struct FHairAdvancedRenderingSettings final
{
public:
	bool                                          bUseStableRasterization;                           // 0x0000(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bScatterSceneLighting;                             // 0x0001(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FHairAdvancedRenderingSettings;

// ScriptStruct HairStrandsCore.HairGroupsRendering
// 0x0030 (0x0030 - 0x0000)
struct FHairGroupsRendering final
{
public:
	class FName                                   MaterialSlotName;                                  // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInterface*                     Material;                                          // 0x0008(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	struct FHairGeometrySettings                  GeometrySettings;                                  // 0x0010(0x0010)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	struct FHairShadowSettings                    ShadowSettings;                                    // 0x0020(0x000C)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	struct FHairAdvancedRenderingSettings         AdvancedSettings;                                  // 0x002C(0x0002)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_2E[0x2];                                       // 0x002E(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FHairGroupsRendering;

// ScriptStruct HairStrandsCore.GoomBindingGroupInfo
// 0x0010 (0x0010 - 0x0000)
struct FGoomBindingGroupInfo final
{
public:
	int32                                         RenRootCount;                                      // 0x0000(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RenLODCount;                                       // 0x0004(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SimRootCount;                                      // 0x0008(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SimLODCount;                                       // 0x000C(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGoomBindingGroupInfo;

// ScriptStruct HairStrandsCore.GroomAnimationInfo
// 0x0020 (0x0020 - 0x0000)
struct FGroomAnimationInfo final
{
public:
	uint32                                        NumFrames;                                         // 0x0000(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SecondsPerFrame;                                   // 0x0004(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Duration;                                          // 0x0008(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StartTime;                                         // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EndTime;                                           // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         StartFrame;                                        // 0x0014(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EndFrame;                                          // 0x0018(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGroomCacheAttributes                         Attributes;                                        // 0x001C(0x0001)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGroomAnimationInfo;

// ScriptStruct HairStrandsCore.GroomCacheInfo
// 0x0028 (0x0028 - 0x0000)
struct FGroomCacheInfo final
{
public:
	int32                                         Version;                                           // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGroomCacheType                               Type;                                              // 0x0004(0x0001)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGroomAnimationInfo                    AnimationInfo;                                     // 0x0008(0x0020)(Edit, EditConst, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGroomCacheInfo;

// ScriptStruct HairStrandsCore.FollicleMaskOptions
// 0x0010 (0x0010 - 0x0000)
struct FFollicleMaskOptions final
{
public:
	class UGroomAsset*                            Groom;                                             // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, EditConst, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	EFollicleMaskChannel                          Channel;                                           // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FFollicleMaskOptions;

// ScriptStruct HairStrandsCore.GroomHairGroupPreview
// 0x0048 (0x0048 - 0x0000)
struct FGroomHairGroupPreview final
{
public:
	class FName                                   GroupName;                                         // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GroupID;                                           // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CurveCount;                                        // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GuideCount;                                        // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        Attributes;                                        // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        AttributeFlags;                                    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        Flags;                                             // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHairGroupsInterpolation               InterpolationSettings;                             // 0x0020(0x0028)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGroomHairGroupPreview;

// ScriptStruct HairStrandsCore.GroomBuildSettings
// 0x000C (0x000C - 0x0000)
struct FGroomBuildSettings final
{
public:
	bool                                          bOverrideGuides;                                   // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HairToGuideDensity;                                // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGroomInterpolationQuality                    InterpolationQuality;                              // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGroomInterpolationWeight                     InterpolationDistance;                             // 0x0009(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRandomizeGuide;                                   // 0x000A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseUniqueGuide;                                   // 0x000B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGroomBuildSettings;

// ScriptStruct HairStrandsCore.MovieSceneGroomCacheParams
// 0x0020 (0x0020 - 0x0000)
struct FMovieSceneGroomCacheParams
{
public:
	class UGroomCache*                            GroomCache;                                        // 0x0000(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	struct FFrameNumber                           FirstLoopStartFrameOffset;                         // 0x0008(0x0004)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FFrameNumber                           StartFrameOffset;                                  // 0x000C(0x0004)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FFrameNumber                           EndFrameOffset;                                    // 0x0010(0x0004)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PlayRate;                                          // 0x0014(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         bReverse : 1;                                      // 0x0018(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FMovieSceneGroomCacheParams;

// ScriptStruct HairStrandsCore.MovieSceneGroomCacheSectionTemplateParameters
// 0x0008 (0x0028 - 0x0020)
struct FMovieSceneGroomCacheSectionTemplateParameters final : public FMovieSceneGroomCacheParams
{
public:
	struct FFrameNumber                           SectionStartTime;                                  // 0x0020(0x0004)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FFrameNumber                           SectionEndTime;                                    // 0x0024(0x0004)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMovieSceneGroomCacheSectionTemplateParameters;

// ScriptStruct HairStrandsCore.MovieSceneGroomCacheSectionTemplate
// 0x0028 (0x0048 - 0x0020)
struct FMovieSceneGroomCacheSectionTemplate final : public FMovieSceneEvalTemplate
{
public:
	struct FMovieSceneGroomCacheSectionTemplateParameters Params;                                    // 0x0020(0x0028)(NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMovieSceneGroomCacheSectionTemplate;

SDK_NAMESPACE_END
