#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InterchangePipelines

#include "Basic.hpp"

#include "InterchangePipelines_structs.hpp"
#include "InterchangeCore_structs.hpp"
#include "InterchangeCore_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "DeveloperSettings_classes.hpp"
#include "InterchangeFactoryNodes_structs.hpp"
#include "InterchangeNodes_structs.hpp"
#include "InterchangeCommon_structs.hpp"


SDK_NAMESPACE_START

// Class InterchangePipelines.InterchangeGenericCommonMeshesProperties
// 0x0018 (0x0160 - 0x0148)
class UInterchangeGenericCommonMeshesProperties final : public UInterchangePipelineBase
{
public:
	EInterchangeForceMeshType                     ForceAllMeshAsType;                                // 0x0148(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoDetectMeshType;                               // 0x0149(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportLods;                                       // 0x014A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bBakeMeshes;                                       // 0x014B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bBakePivotMeshes;                                  // 0x014C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bKeepSectionsSeparate;                             // 0x014D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EInterchangeVertexColorImportOption           VertexColorImportOption;                           // 0x014E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14F[0x1];                                      // 0x014F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FColor                                 VertexOverrideColor;                               // 0x0150(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRecomputeNormals;                                 // 0x0154(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRecomputeTangents;                                // 0x0155(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseMikkTSpace;                                    // 0x0156(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bComputeWeightedNormals;                           // 0x0157(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseHighPrecisionTangentBasis;                     // 0x0158(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseFullPrecisionUVs;                              // 0x0159(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseBackwardsCompatibleF16TruncUVs;                // 0x015A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRemoveDegenerates;                                // 0x015B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangeGenericCommonMeshesProperties")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangeGenericCommonMeshesProperties")
	}
	static class UInterchangeGenericCommonMeshesProperties* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangeGenericCommonMeshesProperties>();
	}
};
DUMPER7_ASSERTS_UInterchangeGenericCommonMeshesProperties;

// Class InterchangePipelines.InterchangeGenericCommonSkeletalMeshesAndAnimationsProperties
// 0x0010 (0x0158 - 0x0148)
class UInterchangeGenericCommonSkeletalMeshesAndAnimationsProperties final : public UInterchangePipelineBase
{
public:
	bool                                          bImportOnlyAnimations;                             // 0x0148(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_149[0x3];                                      // 0x0149(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TWeakObjectPtr<class USkeleton>               Skeleton;                                          // 0x014C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportMeshesInBoneHierarchy;                      // 0x0154(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseT0AsRefPose;                                   // 0x0155(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bConvertStaticsWithMorphTargetsToSkeletals;        // 0x0156(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_157[0x1];                                      // 0x0157(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangeGenericCommonSkeletalMeshesAndAnimationsProperties")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangeGenericCommonSkeletalMeshesAndAnimationsProperties")
	}
	static class UInterchangeGenericCommonSkeletalMeshesAndAnimationsProperties* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangeGenericCommonSkeletalMeshesAndAnimationsProperties>();
	}
};
DUMPER7_ASSERTS_UInterchangeGenericCommonSkeletalMeshesAndAnimationsProperties;

// Class InterchangePipelines.GLTFPipelineSettings
// 0x0058 (0x0090 - 0x0038)
class UGLTFPipelineSettings final : public UDeveloperSettings
{
public:
	TMap<class FString, struct FSoftObjectPath>   MaterialParents;                                   // 0x0038(0x0050)(Edit, Config, NativeAccessSpecifierPublic)
	uint8                                         Pad_88[0x8];                                       // 0x0088(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GLTFPipelineSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GLTFPipelineSettings")
	}
	static class UGLTFPipelineSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGLTFPipelineSettings>();
	}
};
DUMPER7_ASSERTS_UGLTFPipelineSettings;

// Class InterchangePipelines.InterchangeGLTFPipeline
// 0x0018 (0x0160 - 0x0148)
class UInterchangeGLTFPipeline final : public UInterchangePipelineBase
{
public:
	class FString                                 PipelineDisplayName;                               // 0x0148(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_158[0x8];                                      // 0x0158(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangeGLTFPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangeGLTFPipeline")
	}
	static class UInterchangeGLTFPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangeGLTFPipeline>();
	}
};
DUMPER7_ASSERTS_UInterchangeGLTFPipeline;

// Class InterchangePipelines.MaterialXPipelineSettings
// 0x0140 (0x0178 - 0x0038)
class UMaterialXPipelineSettings final : public UDeveloperSettings
{
public:
	TMap<EInterchangeMaterialXShaders, struct FSoftObjectPath> PredefinedSurfaceShaders;             // 0x0038(0x0050)(Edit, Config, NativeAccessSpecifierPublic)
	TMap<EInterchangeMaterialXBSDF, struct FSoftObjectPath> PredefinedBSDF;                          // 0x0088(0x0050)(Edit, Config, NativeAccessSpecifierPublic)
	TMap<EInterchangeMaterialXEDF, struct FSoftObjectPath> PredefinedEDF;                            // 0x00D8(0x0050)(Edit, Config, NativeAccessSpecifierPublic)
	TMap<EInterchangeMaterialXVDF, struct FSoftObjectPath> PredefinedVDF;                            // 0x0128(0x0050)(Edit, Config, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MaterialXPipelineSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MaterialXPipelineSettings")
	}
	static class UMaterialXPipelineSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMaterialXPipelineSettings>();
	}
};
DUMPER7_ASSERTS_UMaterialXPipelineSettings;

// Class InterchangePipelines.InterchangeMaterialXPipeline
// 0x0008 (0x0150 - 0x0148)
class UInterchangeMaterialXPipeline final : public UInterchangePipelineBase
{
public:
	uint8                                         Pad_148[0x8];                                      // 0x0148(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangeMaterialXPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangeMaterialXPipeline")
	}
	static class UInterchangeMaterialXPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangeMaterialXPipeline>();
	}
};
DUMPER7_ASSERTS_UInterchangeMaterialXPipeline;

// Class InterchangePipelines.InterchangeGenericAnimationPipeline
// 0x0070 (0x01B8 - 0x0148)
class UInterchangeGenericAnimationPipeline final : public UInterchangePipelineBase
{
public:
	TWeakObjectPtr<class UInterchangeGenericCommonSkeletalMeshesAndAnimationsProperties> CommonSkeletalMeshesAndAnimationsProperties; // 0x0148(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class UInterchangeGenericCommonMeshesProperties> CommonMeshesProperties;          // 0x0150(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportAnimations;                                 // 0x0158(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportBoneTracks;                                 // 0x0159(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EInterchangeAnimationRange                    AnimationRange;                                    // 0x015A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15B[0x1];                                      // 0x015B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInt32Interval                         FrameImportRange;                                  // 0x015C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUse30HzToBakeBoneAnimation;                       // 0x0164(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_165[0x3];                                      // 0x0165(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CustomBoneAnimationSampleRate;                     // 0x0168(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSnapToClosestFrameBoundary;                       // 0x016C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportCustomAttribute;                            // 0x016D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAddCurveMetadataToSkeleton;                       // 0x016E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSetMaterialDriveParameterOnCustomAttribute;       // 0x016F(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         MaterialCurveSuffixes;                             // 0x0170(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          bRemoveCurveRedundantKeys;                         // 0x0180(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDoNotImportCurveWithZero;                         // 0x0181(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDeleteExistingNonCurveCustomAttributes;           // 0x0182(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDeleteExistingCustomAttributeCurves;              // 0x0183(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDeleteExistingMorphTargetCurves;                  // 0x0184(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_185[0x3];                                      // 0x0185(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 SourceAnimationName;                               // 0x0188(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSceneImport;                                      // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_199[0x1F];                                     // 0x0199(0x001F)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangeGenericAnimationPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangeGenericAnimationPipeline")
	}
	static class UInterchangeGenericAnimationPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangeGenericAnimationPipeline>();
	}
};
DUMPER7_ASSERTS_UInterchangeGenericAnimationPipeline;

// Class InterchangePipelines.InterchangeGenericAssetsPipeline
// 0x0188 (0x02D0 - 0x0148)
class UInterchangeGenericAssetsPipeline final : public UInterchangePipelineBase
{
public:
	class FString                                 PipelineDisplayName;                               // 0x0148(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EReimportStrategyFlags                        ReimportStrategy;                                  // 0x0158(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseSourceNameForAsset;                            // 0x0159(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15A[0x6];                                      // 0x015A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 AssetName;                                         // 0x0160(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ImportOffsetTranslation;                           // 0x0170(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               ImportOffsetRotation;                              // 0x0188(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	float                                         ImportOffsetUniformScale;                          // 0x01A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A4[0x4];                                      // 0x01A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UInterchangeGenericCommonMeshesProperties* CommonMeshesProperties;                         // 0x01A8(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UInterchangeGenericCommonSkeletalMeshesAndAnimationsProperties* CommonSkeletalMeshesAndAnimationsProperties; // 0x01B0(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UInterchangeGenericMeshPipeline*        MeshPipeline;                                      // 0x01B8(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UInterchangeGenericAnimationPipeline*   AnimationPipeline;                                 // 0x01C0(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UInterchangeGenericMaterialPipeline*    MaterialPipeline;                                  // 0x01C8(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	struct FSoftObjectPath                        ContentPathExistingSkeleton;                       // 0x01D0(0x0020)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportOnlyAnimationAdjusted;                      // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1F1[0xDF];                                     // 0x01F1(0x00DF)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangeGenericAssetsPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangeGenericAssetsPipeline")
	}
	static class UInterchangeGenericAssetsPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangeGenericAssetsPipeline>();
	}
};
DUMPER7_ASSERTS_UInterchangeGenericAssetsPipeline;

// Class InterchangePipelines.InterchangeGenericMaterialPipeline
// 0x00B0 (0x01F8 - 0x0148)
class UInterchangeGenericMaterialPipeline final : public UInterchangePipelineBase
{
public:
	class FString                                 PipelineDisplayName;                               // 0x0148(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportMaterials;                                  // 0x0158(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EInterchangeMaterialSearchLocation            SearchLocation;                                    // 0x0159(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15A[0x6];                                      // 0x015A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 AssetName;                                         // 0x0160(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EInterchangeMaterialImportOption              MaterialImport;                                    // 0x0170(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIdentifyDuplicateMaterials;                       // 0x0171(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCreateMaterialInstanceForParent;                  // 0x0172(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_173[0x5];                                      // 0x0173(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoftObjectPath                        ParentMaterial;                                    // 0x0178(0x0020)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UInterchangeGenericTexturePipeline*     TexturePipeline;                                   // 0x0198(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, ExperimentalNeverOverriden)
	class UInterchangeBaseNodeContainer*          BaseNodeContainer;                                 // 0x01A0(0x0008)(ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, ExperimentalNeverOverriden)
	uint8                                         Pad_1A8[0x50];                                     // 0x01A8(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangeGenericMaterialPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangeGenericMaterialPipeline")
	}
	static class UInterchangeGenericMaterialPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangeGenericMaterialPipeline>();
	}
};
DUMPER7_ASSERTS_UInterchangeGenericMaterialPipeline;

// Class InterchangePipelines.InterchangeGenericMeshPipeline
// 0x00F0 (0x0238 - 0x0148)
class UInterchangeGenericMeshPipeline final : public UInterchangePipelineBase
{
public:
	TWeakObjectPtr<class UInterchangeGenericCommonMeshesProperties> CommonMeshesProperties;          // 0x0148(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class UInterchangeGenericCommonSkeletalMeshesAndAnimationsProperties> CommonSkeletalMeshesAndAnimationsProperties; // 0x0150(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportStaticMeshes;                               // 0x0158(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCombineStaticMeshes;                              // 0x0159(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15A[0x2];                                      // 0x015A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   LODGroup;                                          // 0x015C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoComputeLODScreenSizes;                        // 0x0164(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_165[0x3];                                      // 0x0165(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 LODScreenSizes;                                    // 0x0168(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          bImportCollision;                                  // 0x0178(0x0001)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCollision;                                        // 0x0179(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportCollisionAccordingToMeshName;               // 0x017A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bOneConvexHullPerUCX;                              // 0x017B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EInterchangeMeshCollision                     Collision;                                         // 0x017C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bBuildNanite;                                      // 0x017D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bBuildReversedIndexBuffer;                         // 0x017E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bGenerateLightmapUVs;                              // 0x017F(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSupportFaceRemap;                                 // 0x0180(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_181[0x3];                                      // 0x0181(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MinLightmapResolution;                             // 0x0184(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SrcLightmapIndex;                                  // 0x0188(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DstLightmapIndex;                                  // 0x018C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                BuildScale3D;                                      // 0x0190(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DistanceFieldResolutionScale;                      // 0x01A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class UStaticMesh>             DistanceFieldReplacementMesh;                      // 0x01AC(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxLumenMeshCards;                                 // 0x01B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportSkeletalMeshes;                             // 0x01B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EInterchangeSkeletalMeshContentType           SkeletalMeshImportContentType;                     // 0x01B9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EInterchangeSkeletalMeshContentType           LastSkeletalMeshImportContentType;                 // 0x01BA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCombineSkeletalMeshes;                            // 0x01BB(0x0001)(BlueprintVisible, ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportMorphTargets;                               // 0x01BC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bMergeMorphTargetsWithSameName;                    // 0x01BD(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportVertexAttributes;                           // 0x01BE(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUpdateSkeletonReferencePose;                      // 0x01BF(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCreatePhysicsAsset;                               // 0x01C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C1[0x3];                                      // 0x01C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TWeakObjectPtr<class UPhysicsAsset>           PhysicsAsset;                                      // 0x01C4(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseHighPrecisionSkinWeights;                      // 0x01CC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1CD[0x3];                                      // 0x01CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ThresholdPosition;                                 // 0x01D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ThresholdTangentNormal;                            // 0x01D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ThresholdUV;                                       // 0x01D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MorphThresholdPosition;                            // 0x01DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         BoneInfluenceLimit;                                // 0x01E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1E4[0x54];                                     // 0x01E4(0x0054)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetCombineSkeletalMeshes(bool InbCombineSkeletalMeshes);

	bool GetCombineSkeletalMeshes() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangeGenericMeshPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangeGenericMeshPipeline")
	}
	static class UInterchangeGenericMeshPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangeGenericMeshPipeline>();
	}
};
DUMPER7_ASSERTS_UInterchangeGenericMeshPipeline;

// Class InterchangePipelines.InterchangeGenericLevelPipeline
// 0x0030 (0x0178 - 0x0148)
class UInterchangeGenericLevelPipeline final : public UInterchangePipelineBase
{
public:
	class FString                                 PipelineDisplayName;                               // 0x0148(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EReimportStrategyFlags                        ReimportPropertyStrategy;                          // 0x0158(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EInterchangeSceneHierarchyType                SceneHierarchyType;                                // 0x0159(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDeleteMissingActors;                              // 0x015A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceReimportDeletedActors;                       // 0x015B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceReimportDeletedAssets;                       // 0x015C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDeleteMissingAssets;                              // 0x015D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUsePhysicalInsteadOfStandardPerspectiveCamera;    // 0x015E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_15F[0x19];                                     // 0x015F(0x0019)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangeGenericLevelPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangeGenericLevelPipeline")
	}
	static class UInterchangeGenericLevelPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangeGenericLevelPipeline>();
	}
};
DUMPER7_ASSERTS_UInterchangeGenericLevelPipeline;

// Class InterchangePipelines.InterchangeGenericTexturePipeline
// 0x0068 (0x01B0 - 0x0148)
class UInterchangeGenericTexturePipeline final : public UInterchangePipelineBase
{
public:
	class FString                                 PipelineDisplayName;                               // 0x0148(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImportTextures;                                   // 0x0158(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_159[0x7];                                      // 0x0159(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 AssetName;                                         // 0x0160(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAllowNonPowerOfTwo;                               // 0x0170(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_171[0x7];                                      // 0x0171(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UInterchangeBaseNodeContainer*          BaseNodeContainer;                                 // 0x0178(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, ExperimentalNeverOverriden)
	uint8                                         Pad_180[0x30];                                     // 0x0180(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangeGenericTexturePipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangeGenericTexturePipeline")
	}
	static class UInterchangeGenericTexturePipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangeGenericTexturePipeline>();
	}
};
DUMPER7_ASSERTS_UInterchangeGenericTexturePipeline;

// Class InterchangePipelines.InterchangePipelineMeshesUtilities
// 0x0100 (0x0128 - 0x0028)
class UInterchangePipelineMeshesUtilities final : public UObject
{
public:
	uint8                                         Pad_28[0x100];                                     // 0x0028(0x0100)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UInterchangePipelineMeshesUtilities* CreateInterchangePipelineMeshesUtilities(class UInterchangeBaseNodeContainer* BaseNodeContainer);

	void GetAllMeshGeometry(TArray<class FString>* MeshGeometryUids) const;
	void GetAllMeshGeometryNotInstanced(TArray<class FString>* MeshGeometryUids) const;
	void GetAllMeshInstanceUids(TArray<class FString>* MeshInstanceUids) const;
	void GetAllMeshInstanceUidsUsingMeshGeometryUid(const class FString& MeshGeometryUid, TArray<class FString>* MeshInstanceUids) const;
	void GetAllSkinnedMeshGeometry(TArray<class FString>* MeshGeometryUids) const;
	void GetAllSkinnedMeshInstance(TArray<class FString>* MeshInstanceUids) const;
	void GetAllStaticMeshGeometry(TArray<class FString>* MeshGeometryUids) const;
	void GetAllStaticMeshInstance(TArray<class FString>* MeshInstanceUids) const;
	const struct FInterchangeMeshGeometry GetMeshGeometryByUid(const class FString& MeshGeometryUid) const;
	class FString GetMeshGeometrySkeletonRootUid(const class FString& MeshGeometryUid) const;
	const struct FInterchangeMeshInstance GetMeshInstanceByUid(const class FString& MeshInstanceUid) const;
	class FString GetMeshInstanceSkeletonRootUid(const class FString& MeshInstanceUid) const;
	bool IsValidMeshGeometryUid(const class FString& MeshGeometryUid) const;
	bool IsValidMeshInstanceUid(const class FString& MeshInstanceUid) const;
	void SetContext(const struct FInterchangePipelineMeshesUtilitiesContext& Context) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InterchangePipelineMeshesUtilities")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InterchangePipelineMeshesUtilities")
	}
	static class UInterchangePipelineMeshesUtilities* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterchangePipelineMeshesUtilities>();
	}
};
DUMPER7_ASSERTS_UInterchangePipelineMeshesUtilities;

SDK_NAMESPACE_END
