#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IrisStub

#include "Basic.hpp"


SDK_NAMESPACE_START

// ScriptStruct IrisStub.NetSerializerConfig
// 0x0000 (0x0000 - 0x0000)
#pragma pack(push, 0x1)
struct SDK_ALIGN(0x01) FNetSerializerConfig
{
};
#pragma pack(pop)
DUMPER7_ASSERTS_FNetSerializerConfig;

// ScriptStruct IrisStub.PolymorphicStructNetSerializerConfig
// 0x0001 (0x0001 - 0x0000)
struct FPolymorphicStructNetSerializerConfig : public FNetSerializerConfig
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FPolymorphicStructNetSerializerConfig;

// ScriptStruct IrisStub.PolymorphicArrayStructNetSerializerConfig
// 0x0001 (0x0001 - 0x0000)
struct FPolymorphicArrayStructNetSerializerConfig : public FNetSerializerConfig
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FPolymorphicArrayStructNetSerializerConfig;

SDK_NAMESPACE_END
