#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LiveLinkMovieScene

#include "Basic.hpp"

#include "LiveLinkInterface_structs.hpp"
#include "MovieScene_structs.hpp"
#include "MovieSceneTracks_structs.hpp"


SDK_NAMESPACE_START

// ScriptStruct LiveLinkMovieScene.LiveLinkPropertyData
// 0x0058 (0x0058 - 0x0000)
struct FLiveLinkPropertyData final
{
public:
	class FName                                   PropertyName;                                      // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FMovieSceneFloatChannel>        FloatChannel;                                      // 0x0008(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FMovieSceneStringChannel>       StringChannel;                                     // 0x0018(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FMovieSceneIntegerChannel>      IntegerChannel;                                    // 0x0028(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FMovieSceneBoolChannel>         BoolChannel;                                       // 0x0038(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FMovieSceneByteChannel>         ByteChannel;                                       // 0x0048(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FLiveLinkPropertyData;

// ScriptStruct LiveLinkMovieScene.LiveLinkSubSectionData
// 0x0010 (0x0010 - 0x0000)
struct FLiveLinkSubSectionData final
{
public:
	TArray<struct FLiveLinkPropertyData>          Properties;                                        // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FLiveLinkSubSectionData;

// ScriptStruct LiveLinkMovieScene.MovieSceneLiveLinkSectionTemplate
// 0x0080 (0x00B8 - 0x0038)
struct FMovieSceneLiveLinkSectionTemplate final : public FMovieScenePropertySectionTemplate
{
public:
	struct FLiveLinkSubjectPreset                 SubjectPreset;                                     // 0x0038(0x0038)(NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	TArray<bool>                                  ChannelMask;                                       // 0x0070(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FLiveLinkSubSectionData>        SubSectionsData;                                   // 0x0080(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_90[0x28];                                      // 0x0090(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FMovieSceneLiveLinkSectionTemplate;

SDK_NAMESPACE_END
