#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalDestructibleFoliage

#include "Basic.hpp"

#include "PrimalDestructibleFoliage_classes.hpp"
#include "PrimalDestructibleFoliage_parameters.hpp"


SDK_NAMESPACE_START

// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.BPStartDestruction
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class UGeometryCollection*              destructionAsset                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   HitDirection_0                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Damage_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TotalHealth_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APrimalDestructibleFoliage_C::BPStartDestruction(class UGeometryCollection* destructionAsset, const struct FVector& HitDirection_0, float Damage_0, float TotalHealth_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "BPStartDestruction");

	Params::PrimalDestructibleFoliage_C_BPStartDestruction Parms{};

	Parms.destructionAsset = destructionAsset;
	Parms.HitDirection_0 = std::move(HitDirection_0);
	Parms.Damage_0 = Damage_0;
	Parms.TotalHealth_0 = TotalHealth_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.Break
// (BlueprintCallable, BlueprintEvent)

void APrimalDestructibleFoliage_C::Break()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "Break");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.BreakAllActiveClusters
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGeometryCollectionComponent*     GeoCollection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              DebugTextColor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APrimalDestructibleFoliage_C::BreakAllActiveClusters(class UGeometryCollectionComponent* GeoCollection, const struct FLinearColor& DebugTextColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "BreakAllActiveClusters");

	Params::PrimalDestructibleFoliage_C_BreakAllActiveClusters Parms{};

	Parms.GeoCollection = GeoCollection;
	Parms.DebugTextColor = std::move(DebugTextColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.BreakClusterFromClusterIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGeometryCollectionComponent*     GeoCollection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   ItemIndexOfCluster                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              DebugTextColor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APrimalDestructibleFoliage_C::BreakClusterFromClusterIndex(class UGeometryCollectionComponent* GeoCollection, int32 ItemIndexOfCluster, const struct FLinearColor& DebugTextColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "BreakClusterFromClusterIndex");

	Params::PrimalDestructibleFoliage_C_BreakClusterFromClusterIndex Parms{};

	Parms.GeoCollection = GeoCollection;
	Parms.ItemIndexOfCluster = ItemIndexOfCluster;
	Parms.DebugTextColor = std::move(DebugTextColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.BreakClusterFromClusterIndexArray
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGeometryCollectionComponent*     GeoCollection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TArray<int32>&                          ItemIndexArrayOfCluster                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FLinearColor&              DebugTextColor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APrimalDestructibleFoliage_C::BreakClusterFromClusterIndexArray(class UGeometryCollectionComponent* GeoCollection, TArray<int32>& ItemIndexArrayOfCluster, const struct FLinearColor& DebugTextColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "BreakClusterFromClusterIndexArray");

	Params::PrimalDestructibleFoliage_C_BreakClusterFromClusterIndexArray Parms{};

	Parms.GeoCollection = GeoCollection;
	Parms.ItemIndexArrayOfCluster = std::move(ItemIndexArrayOfCluster);
	Parms.DebugTextColor = std::move(DebugTextColor);

	UObject::ProcessEvent(Func, &Parms);

	ItemIndexArrayOfCluster = std::move(Parms.ItemIndexArrayOfCluster);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.BreakClusterFromRandomClusterIndexArray
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGeometryCollectionComponent*     GeoCollection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TArray<int32>&                          ItemIndexArrayOfCluster                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FLinearColor&              DebugTextColor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  BreakLevelPercent__0_1_                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APrimalDestructibleFoliage_C::BreakClusterFromRandomClusterIndexArray(class UGeometryCollectionComponent* GeoCollection, TArray<int32>& ItemIndexArrayOfCluster, const struct FLinearColor& DebugTextColor, double BreakLevelPercent__0_1_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "BreakClusterFromRandomClusterIndexArray");

	Params::PrimalDestructibleFoliage_C_BreakClusterFromRandomClusterIndexArray Parms{};

	Parms.GeoCollection = GeoCollection;
	Parms.ItemIndexArrayOfCluster = std::move(ItemIndexArrayOfCluster);
	Parms.DebugTextColor = std::move(DebugTextColor);
	Parms.BreakLevelPercent__0_1_ = BreakLevelPercent__0_1_;

	UObject::ProcessEvent(Func, &Parms);

	ItemIndexArrayOfCluster = std::move(Parms.ItemIndexArrayOfCluster);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.BreakSecondLayer
// (BlueprintCallable, BlueprintEvent)

void APrimalDestructibleFoliage_C::BreakSecondLayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "BreakSecondLayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.ExecuteUbergraph_PrimalDestructibleFoliage
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APrimalDestructibleFoliage_C::ExecuteUbergraph_PrimalDestructibleFoliage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "ExecuteUbergraph_PrimalDestructibleFoliage");

	Params::PrimalDestructibleFoliage_C_ExecuteUbergraph_PrimalDestructibleFoliage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.GetDamageThresholdInfo
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGeometryCollectionComponent*     GeoCollection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              DebugTextColor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Damage_Threshold_Array_Length                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APrimalDestructibleFoliage_C::GetDamageThresholdInfo(class UGeometryCollectionComponent* GeoCollection, const struct FLinearColor& DebugTextColor, int32* Damage_Threshold_Array_Length)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "GetDamageThresholdInfo");

	Params::PrimalDestructibleFoliage_C_GetDamageThresholdInfo Parms{};

	Parms.GeoCollection = GeoCollection;
	Parms.DebugTextColor = std::move(DebugTextColor);

	UObject::ProcessEvent(Func, &Parms);

	if (Damage_Threshold_Array_Length != nullptr)
		*Damage_Threshold_Array_Length = Parms.Damage_Threshold_Array_Length;
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.GetLevelFromClusterIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGeometryCollectionComponent*     GeoCollection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   ItemIndexOfCluster                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              DebugTextColor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Level                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APrimalDestructibleFoliage_C::GetLevelFromClusterIndex(class UGeometryCollectionComponent* GeoCollection, int32 ItemIndexOfCluster, const struct FLinearColor& DebugTextColor, int32* Level)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "GetLevelFromClusterIndex");

	Params::PrimalDestructibleFoliage_C_GetLevelFromClusterIndex Parms{};

	Parms.GeoCollection = GeoCollection;
	Parms.ItemIndexOfCluster = ItemIndexOfCluster;
	Parms.DebugTextColor = std::move(DebugTextColor);

	UObject::ProcessEvent(Func, &Parms);

	if (Level != nullptr)
		*Level = Parms.Level;
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.GetRangeOfLevelsFromClusterIndexes
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGeometryCollectionComponent*     GeoCollection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   StartItemIndexOfCluster                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   EndItemIndexOfCluster                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              DebugTextColor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<int32>*                          Level0                                                 (Parm, OutParm)
// TArray<int32>*                          Level1                                                 (Parm, OutParm)
// TArray<int32>*                          Level2                                                 (Parm, OutParm)

void APrimalDestructibleFoliage_C::GetRangeOfLevelsFromClusterIndexes(class UGeometryCollectionComponent* GeoCollection, int32 StartItemIndexOfCluster, int32 EndItemIndexOfCluster, const struct FLinearColor& DebugTextColor, TArray<int32>* Level0, TArray<int32>* Level1, TArray<int32>* Level2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "GetRangeOfLevelsFromClusterIndexes");

	Params::PrimalDestructibleFoliage_C_GetRangeOfLevelsFromClusterIndexes Parms{};

	Parms.GeoCollection = GeoCollection;
	Parms.StartItemIndexOfCluster = StartItemIndexOfCluster;
	Parms.EndItemIndexOfCluster = EndItemIndexOfCluster;
	Parms.DebugTextColor = std::move(DebugTextColor);

	UObject::ProcessEvent(Func, &Parms);

	if (Level0 != nullptr)
		*Level0 = std::move(Parms.Level0);

	if (Level1 != nullptr)
		*Level1 = std::move(Parms.Level1);

	if (Level2 != nullptr)
		*Level2 = std::move(Parms.Level2);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.Group Cluster Index by Level
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGeometryCollectionComponent*     GeoCollection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   NumberOfPiecesInGeoColl                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              DebugTextColor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<int32>*                          Level0                                                 (Parm, OutParm)
// TArray<int32>*                          Level1                                                 (Parm, OutParm)
// TArray<int32>*                          Level2                                                 (Parm, OutParm)

void APrimalDestructibleFoliage_C::Group_Cluster_Index_by_Level(class UGeometryCollectionComponent* GeoCollection, int32 NumberOfPiecesInGeoColl, const struct FLinearColor& DebugTextColor, TArray<int32>* Level0, TArray<int32>* Level1, TArray<int32>* Level2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "Group Cluster Index by Level");

	Params::PrimalDestructibleFoliage_C_Group_Cluster_Index_by_Level Parms{};

	Parms.GeoCollection = GeoCollection;
	Parms.NumberOfPiecesInGeoColl = NumberOfPiecesInGeoColl;
	Parms.DebugTextColor = std::move(DebugTextColor);

	UObject::ProcessEvent(Func, &Parms);

	if (Level0 != nullptr)
		*Level0 = std::move(Parms.Level0);

	if (Level1 != nullptr)
		*Level1 = std::move(Parms.Level1);

	if (Level2 != nullptr)
		*Level2 = std::move(Parms.Level2);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.InitializeVariablesFromGameplayData
// (Public, BlueprintCallable, BlueprintEvent)

void APrimalDestructibleFoliage_C::InitializeVariablesFromGameplayData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "InitializeVariablesFromGameplayData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.OnBreak
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FChaosBreakEvent&          BreakEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference)

void APrimalDestructibleFoliage_C::OnBreak(const struct FChaosBreakEvent& BreakEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "OnBreak");

	Params::PrimalDestructibleFoliage_C_OnBreak Parms{};

	Parms.BreakEvent = std::move(BreakEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APrimalDestructibleFoliage_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PrimalDestructibleFoliage.PrimalDestructibleFoliage_C.StaticBPPreDestructionHandleAttachedComponentClass
// (Event, Public, BlueprintEvent)
// Parameters:
// TSubclassOf<class UActorComponent>      AttachedComponentClass                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// class UInstancedStaticMeshComponent*    ForMeshComp                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   InstancePosition                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FRotator&                  InstanceRotation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   InstanceIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   HitDirection_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Damage_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TotalHealth_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APrimalDestructibleFoliage_C::StaticBPPreDestructionHandleAttachedComponentClass(TSubclassOf<class UActorComponent> AttachedComponentClass, class UInstancedStaticMeshComponent* ForMeshComp, const struct FVector& InstancePosition, const struct FRotator& InstanceRotation, int32 InstanceIndex, const struct FVector& HitDirection_0, float Damage_0, float TotalHealth_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalDestructibleFoliage_C", "StaticBPPreDestructionHandleAttachedComponentClass");

	Params::PrimalDestructibleFoliage_C_StaticBPPreDestructionHandleAttachedComponentClass Parms{};

	Parms.AttachedComponentClass = AttachedComponentClass;
	Parms.ForMeshComp = ForMeshComp;
	Parms.InstancePosition = std::move(InstancePosition);
	Parms.InstanceRotation = std::move(InstanceRotation);
	Parms.InstanceIndex = InstanceIndex;
	Parms.HitDirection_0 = std::move(HitDirection_0);
	Parms.Damage_0 = Damage_0;
	Parms.TotalHealth_0 = TotalHealth_0;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
