#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemWeaponGenericAmmolessConsumeSelf

#include "Basic.hpp"

#include "PrimalItemWeaponGenericNoStats_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemWeaponGenericAmmolessConsumeSelf.PrimalItemWeaponGenericAmmolessConsumeSelf_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemWeaponGenericAmmolessConsumeSelf_C : public UPrimalItemWeaponGenericNoStats_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemWeaponGenericAmmolessConsumeSelf_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemWeaponGenericAmmolessConsumeSelf_C")
	}
	static class UPrimalItemWeaponGenericAmmolessConsumeSelf_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemWeaponGenericAmmolessConsumeSelf_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemWeaponGenericAmmolessConsumeSelf_C;

SDK_NAMESPACE_END
