#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemAmmo_ExplosiveArrow

#include "Basic.hpp"

#include "PrimalItemAmmo_ArrowBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemAmmo_ExplosiveArrow.PrimalItemAmmo_ExplosiveArrow_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemAmmo_ExplosiveArrow_C final : public UPrimalItemAmmo_ArrowBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemAmmo_ExplosiveArrow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemAmmo_ExplosiveArrow_C")
	}
	static class UPrimalItemAmmo_ExplosiveArrow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemAmmo_ExplosiveArrow_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemAmmo_ExplosiveArrow_C;

SDK_NAMESPACE_END
