#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumable_CactusSap

#include "Basic.hpp"

#include "PrimalItemConsumable_Berry_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemConsumable_CactusSap.PrimalItemConsumable_CactusSap_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemConsumable_CactusSap_C final : public UPrimalItemConsumable_Berry_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemConsumable_CactusSap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemConsumable_CactusSap_C")
	}
	static class UPrimalItemConsumable_CactusSap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumable_CactusSap_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemConsumable_CactusSap_C;

SDK_NAMESPACE_END
