#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponGooGun

#include "Basic.hpp"

#include "ShooterGame_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function PrimalItem_WeaponGooGun.PrimalItem_WeaponGooGun_C.ExecuteUbergraph_PrimalItem_WeaponGooGun
// 0x0240 (0x0240 - 0x0000)
struct PrimalItem_WeaponGooGun_C_ExecuteUbergraph_PrimalItem_WeaponGooGun final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_Event_ContextItem;                          // 0x0004(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AShooterPlayerController*               K2Node_Event_ForPC;                                // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FCustomItemData                        CallFunc_GetCustomItemData_OutData;                // 0x0018(0x00A8)()
	bool                                          CallFunc_GetCustomItemData_ReturnValue;            // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue_1;        // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ENetworkModeResult                            CallFunc_IsRunningOnServer_OutNetworkMode;         // 0x00D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D5[0x3];                                       // 0x00D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCustomItemData                        K2Node_MakeStruct_CustomItemData;                  // 0x00E8(0x00A8)()
	struct FCustomItemData                        CallFunc_GetCustomItemData_OutData_1;              // 0x0190(0x00A8)()
	bool                                          CallFunc_GetCustomItemData_ReturnValue_1;          // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PrimalItem_WeaponGooGun_C_ExecuteUbergraph_PrimalItem_WeaponGooGun;

// Function PrimalItem_WeaponGooGun.PrimalItem_WeaponGooGun_C.SelectedCustomContextMenuItem
// 0x0010 (0x0010 - 0x0000)
struct PrimalItem_WeaponGooGun_C_SelectedCustomContextMenuItem final
{
public:
	class FName                                   ContextItem;                                       // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AShooterPlayerController*               ForPC;                                             // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PrimalItem_WeaponGooGun_C_SelectedCustomContextMenuItem;

// Function PrimalItem_WeaponGooGun.PrimalItem_WeaponGooGun_C.BPShouldHideTopLevelCustomContextMenuOption
// 0x0170 (0x0170 - 0x0000)
struct PrimalItem_WeaponGooGun_C_BPShouldHideTopLevelCustomContextMenuOption final
{
public:
	class FName                                   ContextItem;                                       // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCustomItemData                        CallFunc_GetCustomItemData_OutData;                // 0x0010(0x00A8)()
	bool                                          CallFunc_GetCustomItemData_ReturnValue;            // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCustomItemData                        CallFunc_GetCustomItemData_OutData_1;              // 0x00C0(0x00A8)()
	bool                                          CallFunc_GetCustomItemData_ReturnValue_1;          // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue_1;        // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PrimalItem_WeaponGooGun_C_BPShouldHideTopLevelCustomContextMenuOption;

// Function PrimalItem_WeaponGooGun.PrimalItem_WeaponGooGun_C.IsCustomContextMenuItemEnabled
// 0x000C (0x000C - 0x0000)
struct PrimalItem_WeaponGooGun_C_IsCustomContextMenuItemEnabled final
{
public:
	class FName                                   ContextItem;                                       // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PrimalItem_WeaponGooGun_C_IsCustomContextMenuItemEnabled;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
