#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SP_Interpolators

#include "Basic.hpp"

#include "SP_Interpolators_classes.hpp"
#include "SP_Interpolators_parameters.hpp"


SDK_NAMESPACE_START

// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalAccelInterpolatorFloat
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FAccelerationInterpolatorFloat&  Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// float                                   NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float USPInterpolatorsBPLibrary::EvalAccelInterpolatorFloat(struct FAccelerationInterpolatorFloat& Interpolator, float NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalAccelInterpolatorFloat");

	Params::SPInterpolatorsBPLibrary_EvalAccelInterpolatorFloat Parms{};

	Parms.Interpolator = std::move(Interpolator);
	Parms.NewGoal = NewGoal;
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalAccelInterpolatorRotator
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct FAccelerationInterpolatorRotator&Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// const struct FRotator&                  NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FRotator                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FRotator USPInterpolatorsBPLibrary::EvalAccelInterpolatorRotator(struct FAccelerationInterpolatorRotator& Interpolator, const struct FRotator& NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalAccelInterpolatorRotator");

	Params::SPInterpolatorsBPLibrary_EvalAccelInterpolatorRotator Parms{};

	Parms.Interpolator = std::move(Interpolator);
	Parms.NewGoal = std::move(NewGoal);
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalAccelInterpolatorVector
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct FAccelerationInterpolatorVector& Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// const struct FVector&                   NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector USPInterpolatorsBPLibrary::EvalAccelInterpolatorVector(struct FAccelerationInterpolatorVector& Interpolator, const struct FVector& NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalAccelInterpolatorVector");

	Params::SPInterpolatorsBPLibrary_EvalAccelInterpolatorVector Parms{};

	Parms.Interpolator = std::move(Interpolator);
	Parms.NewGoal = std::move(NewGoal);
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalCritDampedSpringInterpolatorRotator
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct FCritDampSpringInterpolatorRotator*Interpolator                                           (Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
// const struct FRotator&                  NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FRotator                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FRotator USPInterpolatorsBPLibrary::EvalCritDampedSpringInterpolatorRotator(struct FCritDampSpringInterpolatorRotator* Interpolator, const struct FRotator& NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalCritDampedSpringInterpolatorRotator");

	Params::SPInterpolatorsBPLibrary_EvalCritDampedSpringInterpolatorRotator Parms{};

	Parms.NewGoal = std::move(NewGoal);
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Interpolator != nullptr)
		*Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalCritDampedSpringInterpolatorVector
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct FCritDampSpringInterpolatorVector*Interpolator                                           (Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
// const struct FVector&                   NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector USPInterpolatorsBPLibrary::EvalCritDampedSpringInterpolatorVector(struct FCritDampSpringInterpolatorVector* Interpolator, const struct FVector& NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalCritDampedSpringInterpolatorVector");

	Params::SPInterpolatorsBPLibrary_EvalCritDampedSpringInterpolatorVector Parms{};

	Parms.NewGoal = std::move(NewGoal);
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Interpolator != nullptr)
		*Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalDoubleIIRInterpolatorFloat
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FDoubleIIRInterpolatorFloat&     Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// float                                   NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float USPInterpolatorsBPLibrary::EvalDoubleIIRInterpolatorFloat(struct FDoubleIIRInterpolatorFloat& Interpolator, float NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalDoubleIIRInterpolatorFloat");

	Params::SPInterpolatorsBPLibrary_EvalDoubleIIRInterpolatorFloat Parms{};

	Parms.Interpolator = std::move(Interpolator);
	Parms.NewGoal = NewGoal;
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalDoubleIIRInterpolatorRotator
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct FDoubleIIRInterpolatorRotator&   Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// const struct FRotator&                  NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FRotator                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FRotator USPInterpolatorsBPLibrary::EvalDoubleIIRInterpolatorRotator(struct FDoubleIIRInterpolatorRotator& Interpolator, const struct FRotator& NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalDoubleIIRInterpolatorRotator");

	Params::SPInterpolatorsBPLibrary_EvalDoubleIIRInterpolatorRotator Parms{};

	Parms.Interpolator = std::move(Interpolator);
	Parms.NewGoal = std::move(NewGoal);
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalDoubleIIRInterpolatorVector
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct FDoubleIIRInterpolatorVector&    Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// const struct FVector&                   NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector USPInterpolatorsBPLibrary::EvalDoubleIIRInterpolatorVector(struct FDoubleIIRInterpolatorVector& Interpolator, const struct FVector& NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalDoubleIIRInterpolatorVector");

	Params::SPInterpolatorsBPLibrary_EvalDoubleIIRInterpolatorVector Parms{};

	Parms.Interpolator = std::move(Interpolator);
	Parms.NewGoal = std::move(NewGoal);
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalIIRInterpolatorFloat
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FIIRInterpolatorFloat&           Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// float                                   NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float USPInterpolatorsBPLibrary::EvalIIRInterpolatorFloat(struct FIIRInterpolatorFloat& Interpolator, float NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalIIRInterpolatorFloat");

	Params::SPInterpolatorsBPLibrary_EvalIIRInterpolatorFloat Parms{};

	Parms.Interpolator = std::move(Interpolator);
	Parms.NewGoal = NewGoal;
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalIIRInterpolatorRotator
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct FIIRInterpolatorRotator&         Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// const struct FRotator&                  NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FRotator                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FRotator USPInterpolatorsBPLibrary::EvalIIRInterpolatorRotator(struct FIIRInterpolatorRotator& Interpolator, const struct FRotator& NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalIIRInterpolatorRotator");

	Params::SPInterpolatorsBPLibrary_EvalIIRInterpolatorRotator Parms{};

	Parms.Interpolator = std::move(Interpolator);
	Parms.NewGoal = std::move(NewGoal);
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.EvalIIRInterpolatorVector
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct FIIRInterpolatorVector&          Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// const struct FVector&                   NewGoal                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector USPInterpolatorsBPLibrary::EvalIIRInterpolatorVector(struct FIIRInterpolatorVector& Interpolator, const struct FVector& NewGoal, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "EvalIIRInterpolatorVector");

	Params::SPInterpolatorsBPLibrary_EvalIIRInterpolatorVector Parms{};

	Parms.Interpolator = std::move(Interpolator);
	Parms.NewGoal = std::move(NewGoal);
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);

	return Parms.ReturnValue;
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetAccelInterpolatorFloat
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FAccelerationInterpolatorFloat&  Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetAccelInterpolatorFloat(struct FAccelerationInterpolatorFloat& Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetAccelInterpolatorFloat");

	Params::SPInterpolatorsBPLibrary_ResetAccelInterpolatorFloat Parms{};

	Parms.Interpolator = std::move(Interpolator);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetAccelInterpolatorRotator
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FAccelerationInterpolatorRotator&Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetAccelInterpolatorRotator(struct FAccelerationInterpolatorRotator& Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetAccelInterpolatorRotator");

	Params::SPInterpolatorsBPLibrary_ResetAccelInterpolatorRotator Parms{};

	Parms.Interpolator = std::move(Interpolator);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetAccelInterpolatorVector
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FAccelerationInterpolatorVector& Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetAccelInterpolatorVector(struct FAccelerationInterpolatorVector& Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetAccelInterpolatorVector");

	Params::SPInterpolatorsBPLibrary_ResetAccelInterpolatorVector Parms{};

	Parms.Interpolator = std::move(Interpolator);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetCritDampedSpringInterpolatorRotator
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FCritDampSpringInterpolatorRotator*Interpolator                                           (Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetCritDampedSpringInterpolatorRotator(struct FCritDampSpringInterpolatorRotator* Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetCritDampedSpringInterpolatorRotator");

	Params::SPInterpolatorsBPLibrary_ResetCritDampedSpringInterpolatorRotator Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Interpolator != nullptr)
		*Interpolator = std::move(Parms.Interpolator);
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetCritDampedSpringInterpolatorVector
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FCritDampSpringInterpolatorVector*Interpolator                                           (Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetCritDampedSpringInterpolatorVector(struct FCritDampSpringInterpolatorVector* Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetCritDampedSpringInterpolatorVector");

	Params::SPInterpolatorsBPLibrary_ResetCritDampedSpringInterpolatorVector Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Interpolator != nullptr)
		*Interpolator = std::move(Parms.Interpolator);
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetDoubleIIRInterpolatorFloat
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FDoubleIIRInterpolatorFloat&     Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetDoubleIIRInterpolatorFloat(struct FDoubleIIRInterpolatorFloat& Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetDoubleIIRInterpolatorFloat");

	Params::SPInterpolatorsBPLibrary_ResetDoubleIIRInterpolatorFloat Parms{};

	Parms.Interpolator = std::move(Interpolator);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetDoubleIIRInterpolatorRotator
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FDoubleIIRInterpolatorRotator&   Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetDoubleIIRInterpolatorRotator(struct FDoubleIIRInterpolatorRotator& Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetDoubleIIRInterpolatorRotator");

	Params::SPInterpolatorsBPLibrary_ResetDoubleIIRInterpolatorRotator Parms{};

	Parms.Interpolator = std::move(Interpolator);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetDoubleIIRInterpolatorVector
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FDoubleIIRInterpolatorVector&    Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetDoubleIIRInterpolatorVector(struct FDoubleIIRInterpolatorVector& Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetDoubleIIRInterpolatorVector");

	Params::SPInterpolatorsBPLibrary_ResetDoubleIIRInterpolatorVector Parms{};

	Parms.Interpolator = std::move(Interpolator);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetIIRInterpolatorFloat
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FIIRInterpolatorFloat&           Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetIIRInterpolatorFloat(struct FIIRInterpolatorFloat& Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetIIRInterpolatorFloat");

	Params::SPInterpolatorsBPLibrary_ResetIIRInterpolatorFloat Parms{};

	Parms.Interpolator = std::move(Interpolator);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetIIRInterpolatorRotator
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FIIRInterpolatorRotator&         Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetIIRInterpolatorRotator(struct FIIRInterpolatorRotator& Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetIIRInterpolatorRotator");

	Params::SPInterpolatorsBPLibrary_ResetIIRInterpolatorRotator Parms{};

	Parms.Interpolator = std::move(Interpolator);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);
}


// Function SP_Interpolators.SPInterpolatorsBPLibrary.ResetIIRInterpolatorVector
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FIIRInterpolatorVector&          Interpolator                                           (Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void USPInterpolatorsBPLibrary::ResetIIRInterpolatorVector(struct FIIRInterpolatorVector& Interpolator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SPInterpolatorsBPLibrary", "ResetIIRInterpolatorVector");

	Params::SPInterpolatorsBPLibrary_ResetIIRInterpolatorVector Parms{};

	Parms.Interpolator = std::move(Interpolator);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	Interpolator = std::move(Parms.Interpolator);
}


SDK_NAMESPACE_END
