#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_SummoningSickness

#include "Basic.hpp"

#include "Buff_SummoningSickness_classes.hpp"
#include "Buff_SummoningSickness_parameters.hpp"


SDK_NAMESPACE_START

// Function Buff_SummoningSickness.Buff_SummoningSickness_C.BPDeactivated
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           ForInstigator                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABuff_SummoningSickness_C::BPDeactivated(class AActor* ForInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_SummoningSickness_C", "BPDeactivated");

	Params::Buff_SummoningSickness_C_BPDeactivated Parms{};

	Parms.ForInstigator = ForInstigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_SummoningSickness.Buff_SummoningSickness_C.BPPreSetupForInstigator
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           ForInstigator                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABuff_SummoningSickness_C::BPPreSetupForInstigator(class AActor* ForInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_SummoningSickness_C", "BPPreSetupForInstigator");

	Params::Buff_SummoningSickness_C_BPPreSetupForInstigator Parms{};

	Parms.ForInstigator = ForInstigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_SummoningSickness.Buff_SummoningSickness_C.BPPreventAddingOtherBuff
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class APrimalBuff>          anotherBuffClass                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABuff_SummoningSickness_C::BPPreventAddingOtherBuff(TSubclassOf<class APrimalBuff> anotherBuffClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_SummoningSickness_C", "BPPreventAddingOtherBuff");

	Params::Buff_SummoningSickness_C_BPPreventAddingOtherBuff Parms{};

	Parms.anotherBuffClass = anotherBuffClass;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Buff_SummoningSickness.Buff_SummoningSickness_C.BuffAdjustDamage
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                HitInfo                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class AController*                      EventInstigator                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           TheDamageCauser                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class UDamageType>          TheDamgeType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float ABuff_SummoningSickness_C::BuffAdjustDamage(float Damage, const struct FHitResult& HitInfo, class AController* EventInstigator, class AActor* TheDamageCauser, TSubclassOf<class UDamageType> TheDamgeType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_SummoningSickness_C", "BuffAdjustDamage");

	Params::Buff_SummoningSickness_C_BuffAdjustDamage Parms{};

	Parms.Damage = Damage;
	Parms.HitInfo = std::move(HitInfo);
	Parms.EventInstigator = EventInstigator;
	Parms.TheDamageCauser = TheDamageCauser;
	Parms.TheDamgeType = TheDamgeType;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Buff_SummoningSickness.Buff_SummoningSickness_C.DrawBuffFloatingHUD
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   BuffIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AShooterHUD*                      HUD                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   CenterX                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CenterY                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DrawScale                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuff_SummoningSickness_C::DrawBuffFloatingHUD(int32 BuffIndex, class AShooterHUD* HUD, float CenterX, float CenterY, float DrawScale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_SummoningSickness_C", "DrawBuffFloatingHUD");

	Params::Buff_SummoningSickness_C_DrawBuffFloatingHUD Parms{};

	Parms.BuffIndex = BuffIndex;
	Parms.HUD = HUD;
	Parms.CenterX = CenterX;
	Parms.CenterY = CenterY;
	Parms.DrawScale = DrawScale;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
