#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUDActiveMissionAlertEntry

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass HUDActiveMissionAlertEntry.HUDActiveMissionAlertEntry_C
// 0x0020 (0x0388 - 0x0368)
class UHUDActiveMissionAlertEntry_C final : public UUserWidget
{
public:
	class UTextBlock*                             AlertContentTextBlock;                             // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             AlertCountTextBlock;                               // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 AlertEntryIcon;                                    // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               AlertEntryIconContainer;                           // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HUDActiveMissionAlertEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HUDActiveMissionAlertEntry_C")
	}
	static class UHUDActiveMissionAlertEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUDActiveMissionAlertEntry_C>();
	}
};
DUMPER7_ASSERTS_UHUDActiveMissionAlertEntry_C;

SDK_NAMESPACE_END
