#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_WoodRailing

#include "Basic.hpp"

#include "PrimalItemStructure_BaseRailing_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemStructure_WoodRailing.PrimalItemStructure_WoodRailing_C
// 0x0000 (0x0B90 - 0x0B90)
class UPrimalItemStructure_WoodRailing_C final : public UPrimalItemStructure_BaseRailing_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_WoodRailing_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemStructure_WoodRailing_C")
	}
	static class UPrimalItemStructure_WoodRailing_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_WoodRailing_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemStructure_WoodRailing_C;

SDK_NAMESPACE_END
