#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TribeMemberButton

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass TribeMemberButton.TribeMemberButton_C
// 0x0038 (0x0860 - 0x0828)
class UTribeMemberButton_C final : public UTribeMemberButtonWidget
{
public:
	class UCustomButtonWidget*                    Button;                                            // 0x0828(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FLinearColor                           SelectedColorBG;                                   // 0x0830(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           UnSelectedPairColorBG;                             // 0x0840(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           UnSelectedColorBG;                                 // 0x0850(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnPaint(struct FPaintContext& Context) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TribeMemberButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TribeMemberButton_C")
	}
	static class UTribeMemberButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTribeMemberButton_C>();
	}
};
DUMPER7_ASSERTS_UTribeMemberButton_C;

SDK_NAMESPACE_END
