#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Option_ModPageCategory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CFCoreWidget_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_Option_ModPageCategory.UI_Option_ModPageCategory_C
// 0x0038 (0x0898 - 0x0860)
class UUI_Option_ModPageCategory_C final : public UCFCoreWidget_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_UI_Option_ModPageCategory_C;        // 0x0860(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHorizontalBox*                         HorizontalBox_31;                                  // 0x0868(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IMG_Icon;                                          // 0x0870(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TEXT_Block;                                        // 0x0878(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 iconUrl;                                           // 0x0880(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UUI_CFCore_StoreMenu_C*                 StoreMenu_Ref;                                     // 0x0890(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_UI_Option_ModPageCategory(int32 EntryPoint);
	void GetRootCFWidget(class UPanelWidget** RootPanelWidget);
	void OnFail_20B338B847EF646EF76186BFC4DF1AD5(class UTexture2DDynamic* Texture);
	void OnSuccess_20B338B847EF646EF76186BFC4DF1AD5(class UTexture2DDynamic* Texture);
	void UpdateThemeSettings();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_Option_ModPageCategory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_Option_ModPageCategory_C")
	}
	static class UUI_Option_ModPageCategory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Option_ModPageCategory_C>();
	}
};
DUMPER7_ASSERTS_UUI_Option_ModPageCategory_C;

SDK_NAMESPACE_END
