#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VehicleTrackFilter_Any

#include "Basic.hpp"

#include "VehicleTrackFilter_ParentClass_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass VehicleTrackFilter_Any.VehicleTrackFilter_Any_C
// 0x0000 (0x0060 - 0x0060)
class UVehicleTrackFilter_Any_C final : public UVehicleTrackFilter_ParentClass_C
{
public:
	bool ShouldActorBeTracked(class AActor* InvestigatedActor, int32 CustomTameSelectionType, int32 DinoGroup, const class FString& CustomTameSearchText, class AShooterGameMode* GameMode, class APlayerState* PlayerState, class AShooterCharacter* Requesting_player_Shooter_Character, bool Debug_Enabled, bool* Handled);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VehicleTrackFilter_Any_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VehicleTrackFilter_Any_C")
	}
	static class UVehicleTrackFilter_Any_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVehicleTrackFilter_Any_C>();
	}
};
DUMPER7_ASSERTS_UVehicleTrackFilter_Any_C;

SDK_NAMESPACE_END
