#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UMG_MPDebugText

#include "Basic.hpp"

#include "BP_UMG_MPDebugText_classes.hpp"
#include "BP_UMG_MPDebugText_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_UMG_MPDebugText.BP_UMG_MPDebugText_C.ExecuteUbergraph_BP_UMG_MPDebugText
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UMG_MPDebugText_C::ExecuteUbergraph_BP_UMG_MPDebugText(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_MPDebugText_C", "ExecuteUbergraph_BP_UMG_MPDebugText");

	Params::BP_UMG_MPDebugText_C_ExecuteUbergraph_BP_UMG_MPDebugText Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UMG_MPDebugText.BP_UMG_MPDebugText_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UMG_MPDebugText_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_MPDebugText_C", "Tick");

	Params::BP_UMG_MPDebugText_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
